### ISSUE TITLE
Left handed Configuration

### ISSUE THREAD

**Issue by eldragon0** [ForFunLabs/ElevenPublicBugsAndAsks#1]
When you switch to left handed control the controller interface stays right handed.

- Pointer stays on left hand even with paddle
- When readjusting the paddle positioning you need to hold the triggers on the right paddle still
- Left controller doesn't show up when adjusting the left handed paddle.

**Comment by DoggyP0O** [comment]
I'd like to add to this:
- Left hand configuration doesn't seem to align with the right hand. Changing one hand does change the other, but they just aren't aligned properly. 
- When changing left hand paddle position, the left paddle is not visible
- as eldragon0 alluded to, controls should mirror when switching hands
- You can't change ball machine when left handed. I need to switch to right hand then switch back.

**Comment by carrotstien** [comment]
should be fixed as of 0.9.3
