### ISSUE TITLE
Bug: Impossible to serve anymore

### ISSUE THREAD

**Issue by EloiStree** [ForFunLabs/ElevenPublicBugsAndAsks#10]
Can't describe a lot because I observe that regularly on people testing the game during the tournament today.
- But basically, player were playing in the main menu or in match against AI.
- After long session:
  - The ball was block to the hand and impossible to use anymore
  - The menu would not appear anymore
To solved, the only possibility was to kill the application and relaunch. 

Happened every 10-20 minutes.

**Comment by carrotstien** [comment]
i think resolved, closing for now
