### ISSUE TITLE
[Index, SteamVR] Haptics too weak

### ISSUE THREAD

**Issue by fholger** [ForFunLabs/ElevenPublicBugsAndAsks#101]
With the Index (Knuckles) controllers, haptics are barely noticable even with power set to max in the debug menu. They are working, in principle; if I balance the ball on the paddle and get a continuous feedback, I can feel it. However, during standard hits, I basically don't feel any feedback.

**Comment by carrotstien** [comment]
should be fixed as of 0.9.3
