### ISSUE TITLE
steam & oculus touch:  problem with A and X as menu buttons during play

### ISSUE THREAD

**Issue by Bubak** [ForFunLabs/ElevenPublicBugsAndAsks#103]
B and Y were better. I've never unintentionally opened the menu with them. Now with A & X all the time.  The same problem as with Oculus and Steam VR system buttons but they could be set as delayed.

**Comment by carrotstien** [comment]
hmm, we might move them around - but also the system is super flexible...so we'll come up with a UI for people to change it as they see fit


that being said, i do agree - I was swinging hard and ended up hitting the menu button. I think we need to add some checks to prevent some controller behavior..that would sort out a lot of problems...


don't open the menu if paddle controller and controller speed >x
don't open menu if trigger is pressing and also pointing at a UI element (so the ball doesn't come to you when you are pointing to the menu

**Comment by carrotstien** [comment]
I have added code to not permit the opening of the menu when the controller is moving faster than .5m/s. This should resolve your issue. Let me know if it doesn't and i'll reopen.

**Comment by Bubak** [comment]
Much better but still 3 times during 20 sets with AI. What about disabling menu button completely during play (between serve and point scoring) on the paddle hand?

**Comment by carrotstien** [comment]
Hmm, that's good idea. Why didn't I think of that :). No reason the menu
should ever be used mid point!

**Comment by carrotstien** [comment]
As soon as I fix all game logic issues, I'll set that as the case

**Comment by Bubak** [comment]
Maybe it's time for this little fix.

**Comment by carrotstien** [comment]
i haven't added this because you need to open the menu to reset the ball when it gets stuck - in those times, you'd still be 'in the point'

I've added it against the AI, will be included in the next push

**Comment by dukeoflegs** [comment]
Closing, remapping can be done in the quest
