### ISSUE TITLE
[0.9.4][rift] unity button -> audio/mic on/off setting not getting saved

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#107]
keeps defaulting to "mic is on" each time the game is launched (even after it was set to "mic is off" in the previous session). but the volume slider setting on that screen seems to be getting saved fine though.

**Comment by carrotstien** [comment]
that is a debug menu, it shouldn't be saved. Anything useful there, will be added to the main menus.
