### ISSUE TITLE
[suggestion] add a value for table height in the menu

### ISSUE THREAD

**Issue by captnchr1s** [ForFunLabs/ElevenPublicBugsAndAsks#110]
One can change the table height in the menu, but it is unclear which value is currently chosen. Great would be a value in meters or centimeters, but also a value between 1 and 20 would help right now from my point of view.

Thanks

**Comment by carrotstien** [comment]
added in v0.25.0

**Comment by ab050505** [comment]
this doesn't seem to be available anymore. i regularly find myself having to re-adjust the table height manually. today i had removed the quest hmd for a few seconds to check my phone and when i put it back on, my head was at the table height. "set floor by touch" seems to set the table too low for me (definitely lower than the recommended 76cm). it would help to have an exact number displayed next to the "player height" slider to show what the current setting value is. this will make it very easy to adjust it manually each time that is needed. currently i have to rely on my best guess. the table being a little lower or a little higher than before might affect the accuracy of my shots.
