### ISSUE TITLE
[suggestion] optional deactivate minimum toss height

### ISSUE THREAD

**Issue by captnchr1s** [ForFunLabs/ElevenPublicBugsAndAsks#111]
I would like to have a checkbox in the menu where i can deactivate the minimum toss height in singleplayer mode.
I think it is annoying for table tennis beginners. Otherwise you could deactivate it only for easy and medium dificulty.

Thanks

**Comment by taiji2078** [comment]
I support this too. The game is too elite players oriented. I appreciate the realism and the effort you put in creating and developing this game, but you take the fun away by making it too realistic in an Arcade environment like the VR, where people come to relax and have fun.

Who wants 100% realism, goes to a club and plays real table tennis.

**Comment by captnchr1s** [comment]
It should be clear that someone who wants the high toss, especially in multiplayer, should get it.
But also someone who is a beginner and wants to do whatever serve he likes, should get this at least in single player. So it must be optional...

**Comment by taiji2078** [comment]
I like the way Beat Saber is taking care of such details. They have a menu where you can tweak your free play mode as much as you like and the score is still being kept.

I'd love something similar in ETT: a menu where you can disable various championship pro restrictions, dedicated to the multiplayer ranked mode. That menu should refer only to single player. 

Basically you have 2 sets of rules: 
1. First set fixed, for multiplayer alone, with all the pro settings enabled;

2. Second set of options, completely editable, for single player only. This way you can disable Toss check, enable some AI help to make the game more arcade and you always hit the ball and the opponent table. This will be the fun Arcade part.

3. A pro simulation vs AI, with all the pro options enforced, where you try to defeat the AI on a scale from 1 to 100 let's say, having an increased difficulty. I really love the ELOS system they use in the best game I play - Ultima Reversi Pro on Android : your winnings will increase the rank and you will always be matched against a better AI, until you get blocked and you face a slightly lower AI and this way the game auto-detects your playing strength and determines your ranking.

This will be your personal single player rank, visible also in the Lobby. The current ranking isn't accurate for a player's skill - it only shows how much time that person has at hand to find other players and play some games against them.
I can play at 6 AM in the morning, when most of the Europe is asleep. I cannot find EU opponents. Playing in lag there is no much chance of getting a high ranking, even if I'm (not) a god of table tennis :))

**Comment by carrotstien** [comment]
1. when you play vs a human, for a ranked match, this rule would 100% have to stay. Serving with a low height is improper and leads to various advantages.
2. for non ranked, or AI play, it can be turned off (not yet, but will be). In fact, in the code, when you start a match, one of the parameters if "strictServingRules".

So yea, what you are saying will happen. 

That being said, you should learn to toss properly. It isn't hard to do unless you've been doing it wrong forever. If this is the case, then if you try to play ranked, you will get penalized all of the time. 

I don't want that either. What do you guys think about:

Serving toss height rules: On, Off, NotificationOnly. 

For ranked, it's locked on On. Anywhere else, you can pick what you want. The last option would let you know that you are serving incorrectly somehow, but not cost you the point. Perhaps, make your tossing controller do a BUZ BUZ BUZ. Or perhaps make the ball change color for a moment.

**Comment by carrotstien** [comment]
for now i have disabled it against ai, and reduced it a lot for MP play. In the future i'll put it back for ranked online play, and as options otherwise
