### ISSUE TITLE
[suggestion] Indicator for serve

### ISSUE THREAD

**Issue by captnchr1s** [ForFunLabs/ElevenPublicBugsAndAsks#113]
I would like to have an indicator for serves on the television, like an icon on either side of the tv.

In matches and especially in multiplayer it happens often, that no one knows who has serve and discussion starts.

Thanks

**Comment by carrotstien** [comment]
good idea! I'll add a little circle or something under someone's name..or maybe a border around their score to denote who is serving.

**Comment by carrotstien** [comment]
added
