### ISSUE TITLE
[Bug] Game thinks that you are your opponent.

### ISSUE THREAD

**Issue by captnchr1s** [ForFunLabs/ElevenPublicBugsAndAsks#114]
If you switch sides in multiplayer and then switch back, in the next game it could that whenever you touch ball the engine thinks that you are your oppenent and gives each point to the player.
The player always wins that 11 0.

**Comment by carrotstien** [comment]
has this been resolved?

**Comment by captnchr1s** [comment]
Still not solved in 0.17.0

**Comment by carrotstien** [comment]
fixed in 0.25.0
