### ISSUE TITLE
[quest][bug][0.10.0]quadrants mini game "end game" button

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#116]
the "end game" button in quadrants mini game doesn't seem to get pressed unless the laser points somewhere in the right half of the button (the button seems to work fine in the other mini games).

**Comment by carrotstien** [comment]
not sure when it was fixed, but just tested on index and it's fixed

**Comment by ab050505** [comment]
(working fine on rift and quest as well now)
