### ISSUE TITLE
[suggestion] AI needs to serve, not give me a free smash

### ISSUE THREAD

**Issue by DoggyP0O** [ForFunLabs/ElevenPublicBugsAndAsks#119]
AI hard and up needs to have a real serve. I feel like it would be pretty easy to implement as well (not that I have any real idea). Just have it vary between  backspin short, backspin long, and fast topspin long. Make sure all the serves a reasonably low to the net as well. 

Maybe hard can be only backspin longs or some more predictable variation. 
Maybe world class or legendary can add in some side spin serves into the pool.
Maybe have common strats like always serve backspin long and backspin short to the leftside with the occasional fast topspin long to the rightside.
Maybe in reverse against lefties 
Maybe make it all optional because I do love using hard AI as a better ball machine.

**Comment by carrotstien** [comment]
big update pushed for AI  including serves
