### ISSUE TITLE
Vers. 0.14.0 Multiplayer Ball disapears

### ISSUE THREAD

**Issue by GeneralFailure-ch** [ForFunLabs/ElevenPublicBugsAndAsks#121]
Played with @A.A.G  and @Frankie69.
While playing a.a.g. it took 5 or 6 serves and the Ball was gone. We exited the Room and came back for antother game. Exactly the same happend after 5 or 6 serves. 
After that I played Frankie96. This Time the Ball disapeared much later, after 3 full games.

**Comment by carrotstien** [comment]
redid the whole game logic system..please let me know if it's not fixed
