### ISSUE TITLE
Vers. 0.14.0 Challenged myself

### ISSUE THREAD

**Issue by GeneralFailure-ch** [ForFunLabs/ElevenPublicBugsAndAsks#122]
Selected myself from the Leaderboard, challenged me and accepted my invite. I had two Paddles and two controllers. Unfortunately I was not able to play against myself (because we where both standing on the same side).

Could not upload Video to betarecordings (i guess because of missing permissions)

**Comment by carrotstien** [comment]
I believe this is fixed, please let me know if it isn't
