### ISSUE TITLE
Vers. 0.14.0 Humming Sound when approching the Ball

### ISSUE THREAD

**Issue by GeneralFailure-ch** [ForFunLabs/ElevenPublicBugsAndAsks#123]
https://drive.google.com/open?id=1S3hydh00V2t55zrxvItVKnb9fn9dXYXH
The sound startet maybe a 20 seconds befor the videocapturing. The sound startet quietly and was then getting louder. Both players did hear the sound.
The humming sound was louder when a Paddle was moving closer to the ball or hitting it. 
After we tossed a second Ball, the sound disapeard (as in the video).

**Comment by carrotstien** [comment]
I have updated teh sound, it should not do that any more
