### ISSUE TITLE
Contrast lighting issue 

### ISSUE THREAD

**Issue by SOUPDOGG** [ForFunLabs/ElevenPublicBugsAndAsks#127]
down wardrobe end, when ball is thrown in air for a corner service ( right handed ) i lose track of ball because of glare from what i pressume is sunlight though window and glare off white beam above, 
Not sure if left handers are having the same problem from bed end

**Comment by GeneralFailure-ch** [comment]
I feel some sort of the same. The illumination in the studio generates many hard shadows even directly on the table. This leads to light/dark color changes and I find this quite irritating during the game. 
In the Legacy version, the solution was excellent solved, with only weak soft shadows and a softer illumination.

**Comment by dukeoflegs** [comment]
Closing, new lighting in game
