### ISSUE TITLE
Incorrect final score on the screen (when game ends)

### ISSUE THREAD

**Issue by Zuorro** [ForFunLabs/ElevenPublicBugsAndAsks#128]
There is a minor bug:
- when  the game finishes the winning side sees final score (11:5) but the loosing side sees previous score (10:5) or (0:0)
and I'm not sure if the correct score is only on a winning side or "serving" side (this one next to the bed since it always serves first)
but there's definitely something going on :smiley: with the screen and final score
*steam version for both players

**Comment by carrotstien** [comment]
i believe this is fixed
