### ISSUE TITLE
WMR - when paddle in left hand, can't toss ball with right hand

### ISSUE THREAD

**Issue by europa16** [ForFunLabs/ElevenPublicBugsAndAsks#129]
In Windows Mixed Reality headset (WMR) (Dell Visor) , when paddle in left hand, can't toss ball with right hand. Does not happen if paddle in right hand and tossing with left hand. I tested to see if same issue arises with Oculus Quest ;  it does not.  ETTVR version on both WMR Dell Visor and Oculus Quest was 0.20 .

**Comment by carrotstien** [comment]
fixed, as of 0.44.2
