### ISSUE TITLE
You instantly enter someones room after you send a challegne (post 0.21.1) 

### ISSUE THREAD

**Issue by 3VERYTHINGISTAKEN** [ForFunLabs/ElevenPublicBugsAndAsks#130]
in my experience, i sent 5 different challenges to 5 different people, and in all the cases, i got into their room instantly.

**Comment by carrotstien** [comment]
wooooooooooooops
![image](https://user-images.githubusercontent.com/234703/63787179-61689d00-c8c1-11e9-9c15-40eb3d6f0e99.png)


i left that on :(

**Comment by carrotstien** [comment]
fixed in 0.25.0
