### ISSUE TITLE
[Suggestion] Serve, service variant

### ISSUE THREAD

**Issue by TomiGotchi** [ForFunLabs/ElevenPublicBugsAndAsks#131]
While first testing the Serve (service of the opponent) always the same Kind, unless Mode.
I would like it (and make it more realistics) if opponent varies in serving first Ball.
Even in the highest Level the Services is poor and never A problem to return.

**Comment by TomiGotchi** [comment]
The Service (first Ball) on highest levels is very poor, so it is possible "easily" to win.
I played about 5-8 games and won on the highest Level.

**Comment by carrotstien** [comment]
Hi - yea this is temporary. Just a placeholder while I sort out other
things.

**Comment by TomiGotchi** [comment]
👍 😁 😁 👍
