### ISSUE TITLE
Index controller table reset not working

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#132]
[11:13 AM]
javidoom:
	Hi!Just tried the positioning pressing every button on the Index controllers... No one moves the table....

**Comment by KristianTashkov** [comment]
I managed to reset my viewpoint with using the left pad, but it was very inconsistent. The legacy approach to table height/distance from player felt a lot more natural.

**Comment by carrotstien** [comment]
fixed, and added legacy methods
