### ISSUE TITLE
AI default position bug

### ISSUE THREAD

**Issue by StownieDaze** [ForFunLabs/ElevenPublicBugsAndAsks#133]
was playing someone online, they left. so i exited the room and went back into free hit mode (perfect AI enabled) but upon returning to free hit the AI's default position had changed to a point abit farther back and to the left (my left, its right) have attached screenshot that shows AI's position and this is where the AI reverted back to after every shot instead of back to the middle of the table. 
![20190906031514_1](https://user-images.githubusercontent.com/52791308/64366616-bfca1400-d055-11e9-917a-577a04dfd88a.jpg)

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
