### ISSUE TITLE
Room scene stairs are in bad position

### ISSUE THREAD

**Issue by bluEEil** [ForFunLabs/ElevenPublicBugsAndAsks#134]
I don't know if it always happens but I noticed it right now. When I play I see stairs going up to my right and they are pretty close (part of the room scene). A lot of times when I play some distance behind my table, and shots go to my right on a wide angle, I stop myself from going to the ball because I'm afraid to hit those stairs. This stairs are to close, they are inside my guardian area (would be cool if they were outssude of it)
Didn't see  way to select the ai skill for home. Not sure what you mean by "issues tracker"

**Comment by carrotstien** [comment]
we can't actually move the stairs or room around. That would take a completely rework of the meshes of the room - and we didn't design it. Some say the bed itself it close as well, but without it looks poor.

In the future there will be other environments that are more open.
