### ISSUE TITLE
controller visible through paddle bug

### ISSUE THREAD

**Issue by StownieDaze** [ForFunLabs/ElevenPublicBugsAndAsks#136]
in game controller was visible through opponents paddle. same bug that was encountered ages ago
![1432f21250137397c2aa613b99847ea9](https://user-images.githubusercontent.com/52791308/64474386-92937800-d1b3-11e9-999b-be873159fbad.jpg)

**Comment by carrotstien** [comment]
i believe this is fixed ? please reopen if not
