### ISSUE TITLE
steamvr controllers not showing up from fresh reboot

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#142]
☬ Zionist ☠ Hunter ☬Today at 5:15 PM
controllers are on. I reboot pc without turning off controllers. I go into steam and click on eleven. when it loads my paddle (right hand) is there just fine, but my left hand does not exist and i cannot spawn ball.
i have to exit game and restart
but my left hand is working just fine in steam menuys. just broken in game

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
