### ISSUE TITLE
Online problems on Quest

### ISSUE THREAD

**Issue by DarkHunter82** [ForFunLabs/ElevenPublicBugsAndAsks#15]
the first problem is the possibility of having notifications for invitations to play.
the second problem is an overlap of the avatar: by explaining myself better, when an opponent connects to the online game everything works well, but if for some reason I go to the oculus home and come back into the game I see the avatar of the player who moves normally but in front of it there is an equal but still one.
third problem is the scoreboard that is not there but this is perhaps because it is not yet implemented.
on the other hand I didn't notice any lag. to play.

**Comment by DarkHunter82** [comment]
the first problem is the possibility of having notifications for invitations to play.
the second problem is an overlap of the avatar: by explaining myself better, when an opponent connects to the online game everything works well, but if for some reason I go to the oculus home and come back into the game I see the avatar of the player who moves normally but in front of it there is an equal but still one.
third problem is the scoreboard that is not there but this is perhaps because it is not yet implemented.
on the other hand I didn't notice any lag.

**Comment by carrotstien** [comment]
closing as most are fixed or NA.
