### ISSUE TITLE
(suggestion) Feedback/confirmation for match challenges sent

### ISSUE THREAD

**Issue by OcularMigraine** [ForFunLabs/ElevenPublicBugsAndAsks#157]
I would like better confirmation that a challenge was successfully sent once the button is clicked. Maybe it could light up, or have a message saying "Challenge sent", or show it under the person's name when you see them listed in the lobby. I believe this could reduce spamming of that button and also just make it clear that it registered.

**Comment by carrotstien** [comment]
hmm, you can't actually spam it - in terms of, it becomes grey. Is it becoming grey not sufficient enough?

**Comment by carrotstien** [comment]
now it says challenge sent
