### ISSUE TITLE
(suggestion) Finding place on leaderboard instantly

### ISSUE THREAD

**Issue by OcularMigraine** [ForFunLabs/ElevenPublicBugsAndAsks#158]
I would like to be able to find my place on the leaderboard really fast, instead of having to scroll down through the list to find my name. Maybe my name could be at the very bottom of the leaderboard and could be clicked on, then the leaderboard would jump to my  position and the other people around me.

**Comment by carrotstien** [comment]
implemented - scoreboard now scrolls to your position by default
