### ISSUE TITLE
[quest(v10)][0.55.0][issue] lobby ai stops responding at some point

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#159]
was hitting with lobby ai. then went into mp lobby. invited somebody there to play. returned to lobby to hit with ai while waiting for the other player to accept the invitation. noticed that ai was no longer responding to my shots.
https://drive.google.com/file/d/1sRgPL3lO-1hytdzpnt0VxbSyknm5I9qY/view?usp=sharing
(logs sent by pm)

**Comment by ab050505** [comment]
this happened again. this time, i did not go into mp lobby or anything. i was just hitting with lobby ai and at one point, as far as i can remember, the ball somehow ended up coming off ai's paddle and went off the table to its right (without crossing the net to my side). after that ai stopped responding to my shots and also stopped auto-serving.
(second set of logs sent by pm)

**Comment by ab050505** [comment]
happened again now. was hitting with lobby ai. opened mp menu. clicked on rooms. dismissed menu. noticed lobby ai no longer responding.
logs:
https://drive.google.com/file/d/18yTxxan3heKkdpiQDDN22WiCbYUBleQg/view?usp=sharing

player logs:
https://drive.google.com/file/d/1pD7Rx6R1ezWGJ2netFDQ6hr1ZcFggAFN/view?usp=sharing

**Comment by carrotstien** [comment]
last push did a lot of work to prevent lobby AI from getting stuck..closing this until future instances
