### ISSUE TITLE
[quest(v10)][0.55.0][issue] win/loss seems to be shown in reverse

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#161]
played a few matches with a player. won every match. happened to check history later and found that the other player has "01" against their name (and i have "00" against mine). though elo numbers seem to indicate that i had won. it all seemed to be working fine in earlier versions (going by earlier history).

**Comment by ab050505** [comment]
played a few with another player later on. lost all matches. and history is now showing win/loss correctly (matches with earlier player no longer visible in history/ seem to have gotten rewritten).

**Comment by ab050505** [comment]
i was playing somebody just now. i remember winning two matches. just after we started the third match, at one point, when i was supposed to serve, i found that i couldn't summon the ball. i tried a couple of times but then suddenly the other player disappeared from the room. i brought up the menu to send logs but the functionality seemed to be disabled (nothing was happening when i clicked on it). i thought, in the latest version, we were supposed to be able to send logs whenever needed. also i just checked history and first of all, it shows only one match having had a result (1-0), with the other being 0-0 (i guess this was the match that got aborted). but, as i said earlier, i seem to remember winning two matches. even with the one match for which it is showing 1-0, it again seems to be showing it in reverse (with 1 for the other player who lost, and 0 for me).

video (see the two most recent matches shown in history):
https://drive.google.com/file/d/1xg68slBxuM3tgUbvMGFnk5EWhIaY7DrX/view?usp=sharing

logs:
https://drive.google.com/file/d/1OWu9fpiQgpgxU2_GEAUm85Uw0JSSpidZ/view?usp=sharing

player logs:
https://drive.google.com/file/d/10SuqCX7B9bO_w4KQrulBcTkmfkJGM6LG/view?usp=sharing

**Comment by ab050505** [comment]
not sure if this was addressed in 0.58 but the issue is still there.

https://drive.google.com/file/d/19qkO5tkv7RM3nIF1ArOEaY5aAHCHWNu6/view?usp=sharing

(i distinctly remember losing the last two matches. but in match history, it says i won the last two matches (but seems to show my elo having decreased as a result). also the "current rank score" in my profile does not seem to match my most recent rank score as shown in match history)

**Comment by carrotstien** [comment]
fixed, but also about to revamp that display anyway
