### ISSUE TITLE
[0.55.0][issue] mask/avatar issue

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#163]
in eleven settings, i've set my mask to the oculus hmd (and that is what it shows in the mirror to the left). but when i play mp, my mask seems to appear to the other player to be the cat mask.

**Comment by gitnull-net** [comment]
Happened to me also (but as the victim with the cat mask next to me). Happened 3 times in a row as I quit the game completely and come back and send a new challenge to the same player.

**Comment by ab050505** [comment]
actually the issue i had described earlier above is somewhat different (the other player sees a different mask than the one which we had selected in game settings). westy seemed to confirm this issue today when he said that his mask is not the cat mask. he seems to have selected some other mask in his game settings but what you saw as his mask was the cat mask instead (stuck next to you). 
the issue which you had faced (wherein the other player's mask was stuck next to you) is more similar to the one mentioned in the last line here (where i had seen the other player's mask stuck to their right side):
https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/197#issuecomment-562994580

**Comment by gitnull-net** [comment]
You're right, it was not only a "not the good mask" issue.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
