### ISSUE TITLE
ball/paddle sound bug

### ISSUE THREAD

**Issue by StownieDaze** [ForFunLabs/ElevenPublicBugsAndAsks#164]
when you drop the ball onto any surface and bring the paddle down on top of it so that the ball glitches through the surface it roboti-fies the collision sound which can be quite startling

**Comment by carrotstien** [comment]
@StownieDaze  not sure if you mean quest or pc. I have just updated the audio buffers so it should be better. 


I have tried pinching the ball against the table, and it does seem a bit louder than it should..but otherwise fine

**Comment by carrotstien** [comment]
closing as this was fixed with one of the latest  audio patches
