### ISSUE TITLE
[Quest][v10][Bug] Sound Quality - Choppy SFX

### ISSUE THREAD

**Issue by lumpthree** [ForFunLabs/ElevenPublicBugsAndAsks#166]
Sound effects are scratchy/low quality through the headphone jack as compared to the quest's built-in speakers (the headphones sound fine in other games).

**Comment by carrotstien** [comment]
that's weird...we aren't (nor can we i believe) know when headphones are plugged in...so your headsphones should sound just like the speaker do...but better

what headphones are you using?

**Comment by lumpthree** [comment]
Yeah I thought it was weird too. I'm using the Vive Deluxe Audio Strap. As soon as I disconnected it and turned up the quest speakers to a similar level it sounded way better. I'll try to replicate it again tonight.

**Comment by lumpthree** [comment]
The sound issues are with the buzzer and ding (miss/score, respectively) SFX. They are not headphone dependent (sorry about that miscue!), they are just more apparent with headphones. Every once in awhile the SFX sound choppy or clipped. Also, smashing the ball resting on the table into the table creates a rather unpleasant sound.

**Comment by carrotstien** [comment]
fixed choppiness..had to do with the audio buffer. So strange that i need a completely different range of values for quest than for pc
