### ISSUE TITLE
[Quest][v10][Bug] Game finished, continues behind menu

### ISSUE THREAD

**Issue by lumpthree** [ForFunLabs/ElevenPublicBugsAndAsks#167]
If I stop a game, or the game ends, selecting a menu option with the trigger causes me to drop/serve the ball (or the AI does do), continuing the game behind the menu.

**Comment by carrotstien** [comment]
hmm, so i was thinking about how to avoid that..but a certain part of the menu, is where you would adjust paddle params...

maybe disable ball toss in all other times..and in those menus.enable it..but disable game events

**Comment by carrotstien** [comment]
semi-fixed ..menu ball toss limited to only certain screens
