### ISSUE TITLE
Enable a button on the non-bat hand to adjust bat orientation

### ISSUE THREAD

**Issue by Llamalland** [ForFunLabs/ElevenPublicBugsAndAsks#171]
The way I hold my controller so that it most closely approximates how I hold a bat, my thumb is held over the grip button (rift controllers), pressing it, so I have to deliberately use an altered grip when adjusting orientation. If a button on the non-bat-hand could be used to hold while adjusting orientation, that would be very helpful.

**Comment by Llamalland** [comment]
https://media.discordapp.net/attachments/340715434099605515/642212055142891540/20191108_142437.jpg?width=484&height=646

**Comment by carrotstien** [comment]
fixed/implemented
