### ISSUE TITLE
Bat/ball sound is too woody, loud and uniform

### ISSUE THREAD

**Issue by Llamalland** [ForFunLabs/ElevenPublicBugsAndAsks#172]
copied from discord: What do other people here think about the sound of bat on ball? I find it's too loud in the first place, but also too woody, almost like a bat with no sponge, and too high pitched. Also it would be awesome if the sound varied with how "brushing" the shot is: compared with a flat perpendicular shot, a brushing shot can have a much lower sound, as much as an octave lower from what I can tell (2:1 frequency ratio).

**Comment by dukeoflegs** [comment]
Closing, new sounds in game
