### ISSUE TITLE
Service indicator

### ISSUE THREAD

**Issue by scrooner** [ForFunLabs/ElevenPublicBugsAndAsks#187]
I'd like to be able to see who's serve it is.  This could be a very tiny indicator on the side of the net, or a dot over the AI's head, or anything really.  I think the only way I can tell who's serve it is now is if I pull the trigger and a ball appears, but that makes for some awkward pauses in the game flow.  If there was a small score indicator on the side of the net where the logo currently sits, that would be a good place for service indicator too.

**Comment by carrotstien** [comment]
in 0.62.1
