### ISSUE TITLE
Show current difficulty level on the scoreboard

### ISSUE THREAD

**Issue by scrooner** [ForFunLabs/ElevenPublicBugsAndAsks#188]
I'd like to be able to see what difficulty level I'm on while playing.  I was having an issue last night where I selected Medium and started the game, but the AI was stuck in Hard mode from the previous session.  I confirmed it by going back into the menu, but I'd rather be able to see this indicated on the scoreboard somewhere.

**Comment by carrotstien** [comment]
in .62.1
