### ISSUE TITLE
[0.56.0][issue] "user is away" message in sp lobby after mp session

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#189]
played somebody for a few matches. the other player indicated they had enough. i exited the mp session. back in sp lobby, found the "user is away" message displayed. tried various things (playing with lobby ai, going into mp lobby, settings etc) but had to finally exit the game and relaunch it to make the message go away.
video and logs here:
https://drive.google.com/drive/folders/1dqJzKEJdbaGQVcw_2v6x-lN78mMwwnPf?usp=sharing

**Comment by ab050505** [comment]
"user is away" was displayed facing the other way. so may be i misread the other player's signal and exited the mp session and the game was trying to show "user is away" to the other player (but i clearly remember explicitly exiting the room (i did not take my hmd off))

**Comment by carrotstien** [comment]
possibly fixed in .62.1

**Comment by carrotstien** [comment]
closing for now as i believe it has been resolved
