### ISSUE TITLE
Legendary AI strangely weak

### ISSUE THREAD

**Issue by Llamalland** [ForFunLabs/ElevenPublicBugsAndAsks#191]
Copied from discord: Legendary AI has some baffling weaknesses. I have little chance in a topspin to topspin battle (as it should be) but I can safely chop (even high arcing chops) almost forever against it without it hitting an attacking shot in response. I am by no means a great chopper, especially in ETT, and I could definitely attack a lot of the chops I was feeding Leg AI.

Leg AI's biggest weakness is serve, of course - it is weak as fuck and any halfway strong player will be able to smash literally every single serve for a winner. It is also quite poor at returning serves.

I like the idea of at least having the option of AIs with specific styles and weaknesses and all that, but the default legendary AI should be able to attack high and medium arcing chops.

**Comment by carrotstien** [comment]
updated AI significantly, please try now
