### ISSUE TITLE
[0.56.0][observation] "user is away" on both sides of the table

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#197]
invited somebody to play. some connection issue (connectiontype:building...). clicked unranked and then tried to practice serving while waiting for connection building to complete. "user is away" message popped up on both sides of the table. finally exited the room as it looked like connection building was not going to complete. 
https://drive.google.com/file/d/1kbe6L3OvMrrV6C7wRnHHUbaQFX0Shtvp/view?usp=sharing

**Comment by ab050505** [comment]
seemed to happen again today (on 0.62.1) with somebody going by the user name mindlesstaco and using quest. this time it seemed to connect fine (though a connectiontype:building issue was resolved via a relay reset around 10 minutes earlier). the other player seemed to leave after trying to serve a few times and failing. "user is away" popped up on both sides of the table initially. then it became "user has left" on their side (don't remember if it had changed to that on my side too). 
https://drive.google.com/file/d/1CVgtItuyso6p7GAaCOzdCcIXkXaiAXXb/view?usp=sharing
(not sure if it's relevant but their cat avatar was stuck at a certain point on their right side (around chest height) throughout)

**Comment by ab050505** [comment]
this happened on 0.85.0 (rift/steam) about half hour back, while playing gingerale. they took off their headset for a few minutes and "user is away" appeared on both sides of the table. i clicked "reset ball and send logs". the "user is away" banners went away after gingerale came back and put on their headset again.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
