### ISSUE TITLE
[0.61.0][issue][rift] crash during mp

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#208]
was playing somebody (fusion something) a few minutes ago. i was on rift and they were on vive. we had just completed a couple of ranked matches and were trying to start another one by clicking on 'ranked' in the menu (as we had done earlier) but somehow in the process the ball ended up hanging in the air next to the other player (whose turn it was to serve). they just couldn't get hold of the ball. i clicked "reset ball" a few times (and i think they did too). we then exited the session. i exited first and as soon as they appeared in the mp lobby, i sent an invitation. not sure if they too tried to do the same at the same time or what but the game just crashed for me and i found myself back at oculus home.  
logs:
https://drive.google.com/file/d/1ihoS8K6DuldoXY0J-laxX1Nbk-zRTLRE/view?usp=sharing

**Comment by carrotstien** [comment]
Ooo, that's a new bug. I have never seen this one before.

Crash!!!
Uploading Crash Report
InvalidOperationException: Invalid binary data stream:
BinaryEntryType.TypeName and BinaryEntryType.TypeID must never be peeked by
the binary reader.
  at Sirenix.Serialization.BinaryDataReader.PeekEntry (System.String& name)
[0x00000] in <00000000000000000000000000000000>:0

hmmm

**Comment by ab050505** [comment]
what xTheRadioStar described in #bugs a couple of hours ago seems similar to this.

**Comment by ab050505** [comment]
something similar happened again today (0.69.0). the ball kept getting stuck a short distance away from the controller after a toss (this happened for both of us). exiting the room and retrying a few times did not help. i also clicked 'reset ball and send logs' a few times. no luck. my game finally crashed when i tried to invite the other player (the other times the other player had invited me). 
logs:
https://drive.google.com/file/d/1kZogcgN6Dd4TIxsCLkuoTi3h-Hch_PMM/view?usp=sharing

**Comment by ab050505** [comment]
(actually the first time around, i was able to toss the ball fine but the ball kept going through my paddle (https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/232). i exited the room. the other player reinvited me from the lobby. then the tossing issue started.)

**Comment by ab050505** [comment]
captn_qrk too was talking about the ball toss issue (my comment above:https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/208#issuecomment-572071933)  in #beta-testers earlier today.

**Comment by carrotstien** [comment]
has this happened since the new release? 78.8

**Comment by ab050505** [comment]
hasn't happened in the few mp games that i've played today (0.80.2)

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
