### ISSUE TITLE
[0.62.1][issue] score not being kept after clicking "continue"

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#209]
while playing easy ai, opting to continue after the first set causes the game to stop keeping score. also ball became unavailable after playing a couple of games in the second set.

**Comment by ab050505** [comment]
logs:
https://drive.google.com/file/d/1s5hUoCc6hTu4fkvUT2PK9XrebGpTpwg7/view?usp=sharing

**Comment by ab050505** [comment]
0.63.2 seems to have resolved this issue (checked on rift/pc). but the continue option seems to appear consistently only after the first game/set. it is not clear (at this point) at what points it is supposed to appear consistently later on. it seems to appear after random numbers of games/sets later on (some times after the third game/set, some times after the fifth and so on (regardless of which side won how many games/sets)).

**Comment by carrotstien** [comment]
i've updated the code for that section.. is this resolved?

**Comment by ab050505** [comment]
tried 0.65.0 now. completed 8 games and started the 9th one before stopping. at the end of each of the first, second and third games, the scoreboard dialog (with "start game" and "change ai" buttons) appeared. but for some reason, it did not appear after the fourth game. it continued straight into the fifth game. i realized that the fifth game had already started only by looking at the score on the tv. it appeared again at the end of the fifth game and did not appear at the end of the 6th, 7th, and 8th games (fwiw, i was playing medium ai and won the 1st, 3rd, 4th, 6th, 7th, 8th games).
also may be the "end game" button on the right can be changed to "end match". this will reflect the fact that clicking that button ends not just the current game but the entire match (it will also match the button on the left that says "restart match").

**Comment by ab050505** [comment]
also fwiw, above, i had started with easy ai initially and then used "change ai" to change to medium ai after playing a couple of games with easy ai (and then played those 8 games with medium ai).
thought i'll try again, this time starting directly with medium ai. completed 3 games and started the 4th one. the score dialog appeared at the end of the first game, but did not appear at the end of the 2nd and 3rd games (i won all 3 of the completed games).

**Comment by ab050505** [comment]
continued playing and completed 6 games (won all) before stopping after completing a couple of points in the 7th game. the score dialog did not appear at the end of the 4th, 5th, and 6th games as well.

**Comment by ab050505** [comment]
this issue (of the "start new game"screen not appearing except at the end of the first game (which is still there as of 0.94.0)) is the reason why i've gotten used to choosing 'restart match' after each game with ai (as i was saying a few minutes ago on discord in the context of the "ai reduce mistake" issue)

**Comment by ab050505** [comment]
working fine now (0.101)
