### ISSUE TITLE
[0.62.1][issue] possible game score issue and ball loss issue in mp

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#210]
while playing fusion5156 just now, at one point the score did not seem to update. we reset the ball and were able to continue (it is possible that there was some serving issue but there was no visible indication of that (at least no prominent indication))
also ball became unavailable at one point (again we reset the ball and were able to continue)
logs:
https://drive.google.com/file/d/1htwFFhLFUVPQbzvLeHtlPSo-L964F-uZ/view?usp=sharing

**Comment by ab050505** [comment]
was playing fusion5156 again just now. after a few matches, at one point, almost in the middle of shot, he suddently disappeared. after a couple of seconds, the game declared me the winner and i could see "user has left" in the background. as per the player log, fusion5156 seems to be mranderson331.
logs:
https://drive.google.com/file/d/1tFgQ4bFsWnRtVMHo5VIK686yJbRJxjoA/view?usp=sharing
(i was just checking the player log to see if there had been some error in the game and found an exception (of course it is possible this exception is normal and thrown when the other side crashes etc.))

**Comment by ab050505** [comment]
(the bit about fusion5156 being mranderson331 can be ignored. turns out i was looking at some old log file: https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/222)

**Comment by carrotstien** [comment]
this is a mixture of a few things, some that are fixed, some, like the user crashing out, harder to pin point. closing for now until more specific incident
