### ISSUE TITLE
[0.62.1][issue][rift] crash while using ball machine

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#211]
not sure if it is relevant but a minute or so before it crashed, there was one of those oculus home reward notifications (as far as i can remember, such notifications did not seem to cause any problems earlier)
logs:
https://drive.google.com/file/d/1t2-UemJs7pZdIWtWZ93hL5MhqB8D8rHt/view?usp=sharing

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
