### ISSUE TITLE
[suggestion] serving fault notification at the net/table

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#212]
this is probably already in the works but serving faults should also be indicated using a message at the net or something (instead of only on the tv).

**Comment by carrotstien** [comment]
will be included in next patch

**Comment by ab050505** [comment]
working in 0.101

**Comment by ab050505** [comment]
actually may be the current net message can be updated to include "(see tv for reason)".
