### ISSUE TITLE
[possible issue] upon launch, game sometimes says i'm offline even when i'm not

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#214]
i am forced to quit the game and relaunch in order to be considered online again.
logs:
https://drive.google.com/file/d/1XgL2VlORj3uHKkkrHyVBPutFCON3otOn/view?usp=sharing

**Comment by carrotstien** [comment]
i'm pretty sure if you got to MP, and enter the lobby, it'd update your
status to online. I did add some logic to try to reconnect to the server,
but maybe it isn't working..will check logs

**Comment by ab050505** [comment]
actually the mp icon too gets disabled when it says offline. so there doesn't seem to be any way to get to the lobby.

**Comment by carrotstien** [comment]
oh, got it.

**Comment by ab050505** [comment]
seemed to happen again. but this time, the mp icon remained enabled. i was able to click on it and go into the mp lobby but then clicking on the 'join lobby' button did not result in anything. logs:
https://drive.google.com/file/d/1lsE0pW9KCquoJ_b8AOrsgihiJIdY0d2H/view?usp=sharing

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
