### ISSUE TITLE
[issue]Friend request menu button lacks feedback

### ISSUE THREAD

**Issue by icsmith** [ForFunLabs/ElevenPublicBugsAndAsks#216]
When I look up a player and want to add them as a friend, I cannot tell if I successfully pressed the button. There's no visual or audio feedback whatsoever.

**Comment by gitnull-net** [comment]
So is the "send challenge" button. For both you have to click a second time to the see the message that it has already been sent.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
