### ISSUE TITLE
[suggestion]See player profiles from match history

### ISSUE THREAD

**Issue by icsmith** [ForFunLabs/ElevenPublicBugsAndAsks#217]
If I had a good match with someone and want to add them after leaving the room, I need to go to match history to see their user name, and then remember the spelling and search from the search menu. It would be better if clicking on the match history block would open your opponent's profile so you could challenge/add them as friend.

**Comment by gitnull-net** [comment]
I agree, scrolling in the whole list of opponents is a pain. Could also add an option to send a friend request in the menu before each match, so no need to go back to the history.

**Comment by carrotstien** [comment]
you can click on the usernames now (you could have done this for a while..just closing as it's not applicable any more)
