### ISSUE TITLE
[repeatable crash] on pc, when pushing ball through table

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#218]
https://streamable.com/2sz2v

**Comment by carrotstien** [comment]
(reported by AAG)

**Comment by ab050505** [comment]
crash doesn't seem to be happening on oculus/rift. if we keep trying to press the ball against the table when it is fairly still, it goes through the paddle one time and then through the table next time.
https://streamable.com/jz4qt
https://streamable.com/rw2wk

**Comment by ab050505** [comment]
(in legacy, the ball seems to go through the table the first time it is pressed again the table)

**Comment by Toelessfoot** [comment]
On Quest in multiplayer - Pressing ball through table didn't cause a crash but the ball disapears, can't be spawned and the players have no choice but to leave the match. Happened twice in 3 matches, wasn't trying to press it through but is what appears to have happened during normal play.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
