### ISSUE TITLE
AI stuck when changing environment on quest

### ISSUE THREAD

**Issue by Talwar85** [ForFunLabs/ElevenPublicBugsAndAsks#22]
Hi,

I had a game vs AI easy and changed the environment from Void to Studio.
After the change my opponent did not move.

V 0.0.1

I had to restart the match.

**Comment by carrotstien** [comment]
this was during an actual single player match right...not just during the hit around?

**Comment by Talwar85** [comment]
@carrotstien  it was during a single player match. I think mode easy

**Comment by carrotstien** [comment]
no more env options for now, so closing
