### ISSUE TITLE
oculus party app seems to mess with performance and mic of Eleven

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#220]
as per blueEE

**Comment by bluEEil** [comment]
To replicate:
1) oculus home
2) Call friend in oculus party
3) Play with friend for 10-20 mins minimum.

Problems caused:
1) Weird lag spikes ir frame drops every few minutes.
2) ETT doesn't detect mic anymore. I'm not sure when this will happen but at some point even if I left the game, restarted quest, uninstall and install ETT again, still no mic in game. Only managed to fix it by going to app permissions, removing mic, going back to app permissions and giving it mic again.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
