### ISSUE TITLE
[possible issue] player log files don't seem to be getting updated

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#222]
i had just played somebody (on beta (0.62.1)) going by the name jakob.binder.5 (or jacob.binder.5). he was on quest/rift s and i was on rift/pc. his mask was stuck to one spot to his right through out. then at one point, he seemed to disappear after opting to start another (unranked) match. there was a "user has left" message on his side. i was just going through the log files to see if there had been any errors and noticed the name mr.anderson331 in player log. i had seen this name a couple of days ago too (after playing somebody else). i then looked at the date modified on the player log files and it is september 18! but the log files under logs folder seem to correctly show today's date for date modified. so looks like player log files (player and player-prev) have not been getting written to since a few days. may be this started happening after i experimented with trying to run both legacy and beta from the same windows account (earlier i used to run only beta in this windows account). i was going through the log files that i've submitted earlier and the player log submitted for [issue 219](https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/219) (submitted 10 days ago) seems to have the correct time stamp (the date modified is the same as the date on which i had submitted the issue). so the player log files stopped getting updated properly some time in the last 10 days. i had experimented with legacy and beta 6 days ago. i had basically uninstalled beta, installed legacy, copied it to another folder, updated to beta and then tried to run legacy from the copied folder (didn't work).
(btw, the accidental push thing had happened 8 days ago. so that too could be the/a reason.)

logs/video:
https://drive.google.com/file/d/1zXtAipfqWz0WB51yn6AJ-CUd9ngA3TaO/view?usp=sharing

**Comment by ab050505** [comment]
my current preference.json file (it is possible i had copied it from an earlier beta version, resulting in logging getting disabled):
https://drive.google.com/file/d/1zIezPu7fBIMP91cjL7OqzuzOT0o8ZPRI/view?usp=sharing

**Comment by carrotstien** [comment]
yea unity might have just changed the location of the player log. Also, the player log for beta is in a different place than the equivalent player log of legacy (due to unity version)

the logging preference from legacy affects only the log.txt file that gets generated

**Comment by ab050505** [comment]
just checked. the correct player log files are indeed there under AppData\LocalLow\For Fun Labs\Eleven now (i remember they used to be only in this location earlier).
