### ISSUE TITLE
ball can't be spawned in single player match when device is offline

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#223]

**Comment by carrotstien** [comment]
fixed, pending release

**Comment by ab050505** [comment]
most likely the above fix applies to this as well but the quadrants mini game too doesn't work when there is no network connection, at least on rift/pc (the other mini games seem to work fine).

**Comment by carrotstien** [comment]
ah thanks, will check there too!

**Comment by carrotstien** [comment]
bam, fixed in local code.

**Comment by ab050505** [comment]
can confirm that 0.63.2 has resolved these issues on rift/pc!
