### ISSUE TITLE
[0.63.2][possible issue] paddle position profiles names inconsistency

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#224]
i had created a paddle position profile in an earlier version of beta on quest. i had named it "gfv". in the current version, it shows this name when i go into paddle settings. but when i click on "edit preset" and then go into paddle position settings (by clicking on the fist icon), it shows the name of that saved profile as "q" (instead of "gfv"). 
(can send video recording if needed)

**Comment by ab050505** [comment]
video:
https://drive.google.com/file/d/1pHxA82QRCdS-kaXTKp1HJEqNsKSvgNXC/view?usp=sharing
(shows 0.63.2 but its the same in 0.64.0 as well)

**Comment by carrotstien** [comment]
fixed
