### ISSUE TITLE
Ability to rotate table with thumbsticks

### ISSUE THREAD

**Issue by devmaxxing** [ForFunLabs/ElevenPublicBugsAndAsks#225]
Seems like we're only able to reposition it by holding down grip button. Would be nice if the table rotated when holding down thumbstick and grip button simultaneously like in normal version.
Use case: I wish to line up the virtual table with the table that I have IRL. Right now the work around is to just to eyeball it, reset, and then reposition.

**Comment by carrotstien** [comment]
> Would be nice if the table rotated when holding down thumbstick and grip button simultaneously like in normal version.

It should be doing this. Can you check again?

**Comment by devmaxxing** [comment]
Thumbstick still not doing anything when I have the grip button down on the Oculus Quest

**Comment by carrotstien** [comment]
but... does grip move the table around? (just confirming). by default, drag positioning is disabled

**Comment by devmaxxing** [comment]
Yeah I enabled dragged positioning in the table settings and then held down grip button with the controller intersecting with the table. Was able to move the table around no problem but when I tried rotating it by moving the thumbstick, nothing happened.

**Comment by carrotstien** [comment]
ooooo i remembered. One of the round buttons are the menu button. the other
one, when held down, resets position. While dragging, if you press that
second button, that will give you the pivot you want. Sorry for the
confusion..i forgot myself :D

**Comment by devmaxxing** [comment]
Alright. I'll close the issue then assuming the controls will be documented somewhere.
