### ISSUE TITLE
Elo system bugged (0.64.0)

### ISSUE THREAD

**Issue by 3VERYTHINGISTAKEN** [ForFunLabs/ElevenPublicBugsAndAsks#227]
Played a lot of matches for 1 hour straight and ended up with no elo gained nor lost.
same thing happened later on, won around 20 games back to back and ended up losing a lot of elo.

**Comment by ironymanvr** [comment]
same here (and others have reported too)

**Comment by carrotstien** [comment]
ELO now working..but match history isn't display very correct info (except ELO)
