### ISSUE TITLE
game doesn't return you to lobby post match when it should

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#230]
![image](https://user-images.githubusercontent.com/234703/71530500-05864300-28b8-11ea-9e8b-f105ae228ce7.png)

**Comment by ab050505** [comment]
related:
https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/144

**Comment by carrotstien** [comment]
@ab050505 ...ah you are right. This is an old issue - i just thought we fixed it. Thanks for adding the reference!

**Comment by ab050505** [comment]
a related issue seems to be that even when we are apparently not in the lobby, we can still if a friend is online (and presumably they can see us as well). noticed this after playing an mp match. clicking on mp icon again brought up the screen with the "join lobby" button. thought i was offline again. but then saw that one of the players listed under friends was shown as online (i had seen the player in the lobby before the mp match (with another player) as well).

**Comment by ab050505** [comment]
![image](https://user-images.githubusercontent.com/28642046/71839511-57617100-30e1-11ea-82a6-8938cabbda3e.png)

**Comment by ab050505** [comment]
the above behavior seems to be as requested in point 17 of https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/184 , except for the lack of an "appear online/offline" option.

**Comment by carrotstien** [comment]
should be fixed now
