### ISSUE TITLE
Ball-racket collisions not registering after exit round, free-hit, accept challenge from another player

### ISSUE THREAD

**Issue by alamarche** [ForFunLabs/ElevenPublicBugsAndAsks#232]
Observed order of operations was as follows:

1. Successfully played many rounds with one player
2. Free hit for a while
3. Accept challenge from another player
4. Start round, other player serves x2 and ball goes through paddle
5. Serve switches to me, same behavior
6. Enter menu, leave menu
7. Paddle has switched hands, still no collisions register.

Throughout this sequence, other player's collisions register normally.

**Comment by carrotstien** [comment]
hmm, when you enter a room in multiplayer, initially you have no racket tangibility. The owner of the room gives it to you programmatically (nothing the user needs to do).

What looks like what happened is that that signal never came across. I'll add some logic to make sure match at least can't start while you have an intangible paddle. 

Have you tried restarting the game and reconnecting?..i think if this does it happen, it should be happening very very rarely. (still should be fixed obviously)

**Comment by alamarche** [comment]
Yes, restarting the game & reconnecting worked (should've mentioned that's how we resolved the issue). Upon restart, paddle hand was still physically on left controller. Settings menu indicated that it was on the right hand. Toggling between left & right in the settings resolved that issue.

Have not yet been able to reproduce the issue. Will reply here if I eventually am.

**Comment by ab050505** [comment]
seemed to happen to me today (on 0.69.0):
https://streamable.com/f533r

the other (most likely quest) player's avatar too was again frozen in place. second time today that its happened to me, out of two mp attempts (again, not sure if it is relevant to the frozen mask issue but both the times, it was the other player that had initiated the session)

**Comment by ab050505** [comment]
third time lucky: was able to play nicoswiss (quest) for half an hour without any issues (this time too, nicoswiss invited me to play (he was using the vr headset mask, btw)).

**Comment by ab050505** [comment]
https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/208#issuecomment-572073847

**Comment by carrotstien** [comment]
has this happened since the new release? 78.8

**Comment by ab050505** [comment]
hasn't happened in the few mp games that i've played today (0.80.2)
