### ISSUE TITLE
Opponent avatar frozen in place on players side

### ISSUE THREAD

**Issue by StownieDaze** [ForFunLabs/ElevenPublicBugsAndAsks#238]
every time upon spawning into an online game with someone, the opponents avatar mask is frozen in place on players side right in front of the table where i imagine their last position was before joining the game, obstructing your own view of the table. the opponent also appears to have no head but can still move around & play as normal.

**Comment by ab050505** [comment]
happened to me too earlier today while playing goblinon, and a couple of other times over the past few weeks with some other players (https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/197#issuecomment-562994580 ). there was one other report where the mask had gotten stuck on the opposite side of the table: https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/163#issuecomment-567445046
https://bit.ly/2QtD9hV

may or may not be relevant but in all the cases where it happened to me, the other player had a quest or a rift s (going by their controllers).

**Comment by ab050505** [comment]
https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/232#issuecomment-571226570

**Comment by carrotstien** [comment]
is this still happening as of 69.0 / 69.1 ?
I hit with AAG and seemed fine

**Comment by ab050505** [comment]
yes, happened to me twice on 69.0 yesterday (the version can be seen in the video here: https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/232#issuecomment-571226570)

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
