### ISSUE TITLE
possible issue with friend requests

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#239]
after we add a friend, apparently the other party needs to accept the friend request before they are added to our friends list. but in my case i don't remember ever having explicitly accepted any friend requests and yet several players are listed under friends for me. not sure how that came about (i had sort of  assumed that we can add friends unilaterally). i tried adding a couple of other players as friends now (by clicking "add friend" on their profile) and they have not appeared in my friends list automatically. when i click "add friend" for them again, it even says there can only be one pending friend request between two players. so apparently my friend request is indeed pending (and not automatically accepted).
(looks like the issue of no feedback for the inital friend request has already been raised: https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/216 )

**Comment by ab050505** [comment]
is it possible that when somebody sends us a friend request, they end up appearing under friends for us but we appear as their friend only after we accept? (just checked my "friend requests" list and it seems to be empty)

**Comment by ab050505** [comment]
some of the players on my friends list have been there for a while and it is possible that i've forgotten having accepted their friend requests via notifications. but a couple of the names are very recent and i don't remember having accepted any friend requests from them (i remember accepting only match requests).

**Comment by carrotstien** [comment]
yea your expectation is correct. Maybe @oscarvazquez  can pull up some logs to see when who friended and who accepted

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
