### ISSUE TITLE
[0.71.1][issue][rift] unable to set paddle position via paddle settings

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#241]
the usual method (pressing the grip button etc) no longer seems to be working.
logs:
https://drive.google.com/file/d/1hgdaD01Wk_IUkafMde7LslJsy3nFNWc2/view?usp=sharing

**Comment by ab050505** [comment]
(managed to get back some of my older paddle positions by using an old paddle json from a backup)

**Comment by ab050505** [comment]
its working fine after turning the "paddle buttons" setting on under controller settings, as suggested on discord. i guess this is set to be off by default in the new settings files (that had overwritten my previous settings files in 0.71.0, apparently by mistake). it might be better to set it to be on by default.

**Comment by carrotstien** [comment]
updated the paddle buttons to be on by default
