### ISSUE TITLE
preset names get messed up "such as saying just Q"

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#242]
2.    Then I tried to save paddle position and created a new preset with some “NAME” but it will be saved as “Q”

**Comment by ab050505** [comment]
related:
https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/224
(fwiw, the json file shows the correct/original preset names)

**Comment by carrotstien** [comment]
still not resolved. It looks like it is attempted to be translated. @oscarvazquez  i don't know where the key field is even being set. I'd adjust it to not try to translate non default preset names

**Comment by carrotstien** [comment]
fixed

**Comment by carrotstien** [comment]
fixed

**Comment by carrotstien** [comment]
fixed
