### ISSUE TITLE
[0.74.0][possible issue] ping showing as 0

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#245]
![image](https://user-images.githubusercontent.com/28642046/72275851-c6484800-3654-11ea-8dcf-b954f6a660d9.png)

![image](https://user-images.githubusercontent.com/28642046/72275870-d3fdcd80-3654-11ea-88ef-3cf334868a66.png)

(there were no other issues during the session (rift vs vive))

**Comment by carrotstien** [comment]
i've gotten 0 ping before...when i'm on the same computer :|

**Comment by ab050505** [comment]
logs:
https://drive.google.com/file/d/1p5YU2zV3n575NJJ11nw3zdvL8wGugv1t/view?usp=sharing

**Comment by ab050505** [comment]
played somebody (most likely on quest, going by the ping fluctuations) a short while ago on 0.77.0. ping seemed to be shown correctly this time.
