### ISSUE TITLE
[0.77][Quest][Issue] Tracking sometime freeze when language is setted to Japanese.

### ISSUE THREAD

**Issue by drive1600** [ForFunLabs/ElevenPublicBugsAndAsks#246]
Quest v0.77, firmware v12
Condition: Language is setted to Japanese (it seems too in Arabic), Not happened in Germany or English.
What: sometime tracking freeze for short time (about 0.5 sec.?).
When: game main info panel opened by press "A" button.
When: lose sound played after I hitted the ball in SP play.

Thnak you very much for support multi language!

**Comment by carrotstien** [comment]
hi. I know about the frame skip when switching to some languages, but i'm
not sure what you mean about the other 2 (when's)

You lose tracking when you open up the main panel and you press A not
aiming at anything?

What do you mean about the lose sound..perhaps you are losing the point?
What does the tv say when you hear that?

**Comment by drive1600** [comment]
Hi, thank you, and you are right! I checked it again.
wrong> When: lose sound played after I hitted the ball in SP play.
right> When: translated point cause message is shown in TV. not happen when the messages not transrated.

**Comment by carrotstien** [comment]
sorry i don't understand what you mean...is there an issue

**Comment by drive1600** [comment]
Thank you so much. The issue I wanted to tell you disappered in v0.110.1 (Quest v14). Please close this ticket. Thank you!

**Comment by drive1600** [comment]
Realy sory to confuse you... I can see the issue today again. v0.110.1 (Quest v14).

**Comment by carrotstien** [comment]
hi @drive1600 ..is the tracking freezing at the moment you changed to japanese..or..after you changed, and moving through the menu?

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
