### ISSUE TITLE
[0.85.0][issue][rift/steam] unable to exit room

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#250]
was playing beta via steam a few minutes ago. while playing westy, looks like there was some network glitch. he appeared frozen initially for a few seconds and then "user has left" appeared. tried to click reset ball but didn't seem to work the first time (so may be the glitch was on my side). worked the next time. but then clicking "exit room" to leave the room did not work. tried a few times (also pressed reset ball a couple more times just to see if it might help but it did not). was able to quit the game altogether however (looks like there was some issue with the "exit room" button in particular).

**Comment by ab050505** [comment]
(btw, i'm using only one controller while playing via steam)

**Comment by carrotstien** [comment]
the code has changed too many times that it is unlikely that this , as is, is reproducible..so closing for now
