### ISSUE TITLE
[0.86.2][issue][rift/steam] ball becomes unavailable in sp 

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#252]
ball became unavailable in sp twice (so far). in both cases, i hit a shot and the ball seemed to take off disproportionately fast towards the clothes area behind ai and then disappear (in one case, i was the one serving and in the other, it was ai)
(note: i'm using a single controller)

video 1 (recorded after the actual event):
https://drive.google.com/file/d/1iFENYxbHjQhaZcvobpQnMVWXWm8XMxLj/view?usp=sharing
logs 1:
https://drive.google.com/file/d/1jpUIOzNerj9RAhOQ6rYU7K0ZW1BPB6IR/view?usp=sharing

video 2 (recorded after the actual event):
https://drive.google.com/file/d/1VNQdhnmtIASM4eGowuTQ6vSIFIo1vnpS/view?usp=sharing
logs 2:
https://drive.google.com/file/d/1ZO9CGyKRqy9pnJ4a9n-SSzcyRKUyo9ox/view?usp=sharing

**Comment by ab050505** [comment]
earlier today, "Kenneth" reported something similar in #general on discord (" the AI seemed to do a SUPERSONIC fast serve, then froze")

**Comment by carrotstien** [comment]
Hmm, the logs you shared contain a lot of logs, I don't know which one is
associated with your issue. I should add a button "share logs", and allow
user to type message, and it'd send the exact log from that moment...that
should make things easier to debug

**Comment by ab050505** [comment]
the "date modified" timestamp on the log files might help (i am recording video and quitting the game pretty much immediately after it happens each time and copying the logs. so the event would've happened within 5 minutes of the "date modified" timestamps).
btw, it happened again within the last 5 minutes. this time the ball seemed to go off the edge of my paddle towards the area behind me. 
logs:
https://drive.google.com/file/d/1B-rZAMOdCXGI_BLubOLbXPFcp7VBcTc8/view?usp=sharing
(i did not even stop to record video this time. so the event of interest might be towards the end of the log files)

**Comment by ab050505** [comment]
(btw, i agree that adding a share logs button in sp too would definitely help)

**Comment by ab050505** [comment]
played for an hour with ai on 0.89.1 today and the issue did not occur.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
