### ISSUE TITLE
Game breaking bug when paddle and table hit ball simultaneously

### ISSUE THREAD

**Issue by Hero-Over** [ForFunLabs/ElevenPublicBugsAndAsks#255]
when my paddle touches the ball at nearly the same time as the ball hits the table, the game does not give any point to victor and also does not load a new ball to serve. once reset ball is hit it will break player movement and both freeze, but voice can be heard.
and during this. the ball reset prompt keeps spamming on the net. even after we leave the match it still occurs

**Comment by carrotstien** [comment]
fixed
