### ISSUE TITLE
[Suggestion] - Individual rubber, spin / speed/ tackiness?

### ISSUE THREAD

**Issue by patrick-lai** [ForFunLabs/ElevenPublicBugsAndAsks#256]
I play TT, In the real world, you will rarely use the same rubber on both sides. So its kind of throwing me off that my backhand feels like my forehand rubber. Suggest, individual adjustment both both sides of the paddle... Sounds like it will be easy to do.

Would be nice if there is also a tackiness setting but we will need to probably figure out what that even means in terms of params/physics.

**Comment by carrotstien** [comment]
@patrick-lai , this is an option already in the revamp. Are you talking about the revamp , or the live version?

**Comment by patrick-lai** [comment]
Hey, sorry I've only been on the live version. Happy for this to be closed if thats the case.
