### ISSUE TITLE
Ball going through paddle/ignoring it

### ISSUE THREAD

**Issue by Talwar85** [ForFunLabs/ElevenPublicBugsAndAsks#26]
When holding the paddle upsidedown with the black side in direction to the oppent it seems like the ball is ignoring the paddle under various circumstances.

The paddle was maybe in 10-15 degress in my direction.
       
                          |  |
                          |  |
                          |  |
                      .'::::::::::`.
                    /:::::::.--.:::::\
                   /:::::::(    ):::::\
                   |::::::::`--'::::::|
                   \:::::::::::::::::/
                     `::::::::::::::'

**Comment by carrotstien** [comment]
this may just be an illusion of proprioception. As in, you may be swinging and thinking the paddle and ball have a certain relationship, but they actually don't. 

Though it could definitely be a physics bug - but unfortunately, until I re-implement the replay system it would be very hard to verify and handle this bug.

**Comment by carrotstien** [comment]
can't replicate, either fixed or not an issue, closing
