### ISSUE TITLE
Blade and table collision physics 

### ISSUE THREAD

**Issue by issis74** [ForFunLabs/ElevenPublicBugsAndAsks#262]
Tried Boneworks and I really liked how objects don't go through each other, rather they bump/collide.
It would be good if a similar type of physics is implemented for the table - paddle interaction in Eleven. It breaks immersion plus it makes possible some unrealistic shots when the paddle goes through the table.

**Comment by carrotstien** [comment]
yea for sure we'll be adding this - specifically because we've found that there are many instances of people moving through the table to hit the ball

**Comment by carrotstien** [comment]
closing as same as #106

**Comment by carrotstien** [comment]
closing as same as #106

**Comment by carrotstien** [comment]
closing as same as #106
