### ISSUE TITLE
Add a Clock 

### ISSUE THREAD

**Issue by MellowMagi** [ForFunLabs/ElevenPublicBugsAndAsks#264]
It would be great to have a clock on the television to keep track of the time while in a match

**Comment by ANewDawn** [comment]
Or even a real time clock on the wall even better

**Comment by jgoldsmith613** [comment]
I think it be cooler to have a watch on your non paddle hand.  I always wear one, and looked at my wrist by accident expecting to see the time.

**Comment by carrotstien** [comment]
i've added a clock to the menu for now. Watches/in room clock will/may be added later depending on the environment.
