### ISSUE TITLE
Frequent Crashed on the Oculus Quest!!

### ISSUE THREAD

**Issue by robocor1** [ForFunLabs/ElevenPublicBugsAndAsks#266]
Just bought this and found the game to be very unstable!! Numerous crashes one of which completely froze my headset and others where the game reported conflict issues with the guardian.  Developerhas responded quickly to my review on Oculus store. Had offered “free access” as issue is investigated. Not sure how this works?

**Comment by carrotstien** [comment]
Hi, just waking up now. That was I who wrote that on the review response.

Thanks for coming here. I'll message you in a while.

**Comment by carrotstien** [comment]
Hi, so i'd just need your quest email address to add you to the beta. Meanwhile, I have reached out to oculus. if we can set up logging on your quest, and you capture a crash, and we can send that over, that would be very helpful 

please reach out to me (carrotstien) on discord https://discord.gg/v8bwdwf so we can chat live on this

**Comment by robocor1** [comment]
Hi

Thanks for getting back to me.

My email address is  robashcorlett@gmail.com

Many thanks

Rob

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
