### ISSUE TITLE
Lower net post so it's flush with the net

### ISSUE THREAD

**Issue by Llamalland** [ForFunLabs/ElevenPublicBugsAndAsks#267]
https://www.youtube.com/watch?v=8B5JGatWjcI (not my video, but I had the exact same thing happen to me too). Obvously this is legal, but I've never seen it at all IRL in decades of playing because the net post is flush with the net. Should be pretty easily avoidable.

**Comment by Llamalland** [comment]
It's not the height that's the problem, I believe. It's the width.

**Comment by carrotstien** [comment]
https://www.facebook.com/TableTennisDaily/videos/245070259964950/  :)

**Comment by Llamalland** [comment]
Exactly!

**Comment by carrotstien** [comment]
closing because it's legal as per the video :P (just part of some cleanup)
