### ISSUE TITLE
Enable sortable leaderboard

### ISSUE THREAD

**Issue by SaltTheSnail** [ForFunLabs/ElevenPublicBugsAndAsks#273]
-Enable Leaderboard to be sortable to those that are currently Online (or in Lobby) - or display the names of those Online differently (highlighted, maybe?)

Carrotstien thoughts - we definitely should sort leaderboard by applicable users (so if a user never played ranked, they shouldn't be in the ELO leaderboard). Sorting or highlighting online is a good idea.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
