### ISSUE TITLE
Challenging online players not in Lobby

### ISSUE THREAD

**Issue by SaltTheSnail** [ForFunLabs/ElevenPublicBugsAndAsks#274]
-Allow challenges to other players that are currently online but in a current match (for when a similarly matched opponent is online but you just cant seem to cross paths with them in the lobby)

Carrotstien thoughts - there are two ways to do this: either - auto challenge upon room exit..or some sort of "i call next". The first is relatively easy to do, the second requires a bunch of extra logic

**Comment by Llamalland** [comment]
I'd really like a "I challenge the winner" option, since that's the general etiquette for introducing yourself to unfamiliar table tennis players.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
