### ISSUE TITLE
Improved self-stats page

### ISSUE THREAD

**Issue by SaltTheSnail** [ForFunLabs/ElevenPublicBugsAndAsks#276]
- Currently unable to see own win/loss record. As many stats as can be provided really, is always a fun thing.

**Comment by GeneralFailure-ch** [comment]
Would also be nice to know youre own Rank in comparsion to the total ammount of players 
For example as in Legacy: Rank 55 from a total of 12'000 -> 55/12'000

**Comment by dukeoflegs** [comment]
Closing, UI updated
