### ISSUE TITLE
Wide FOV over-aggressive occlusion culling

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#277]
Fusion
#1274

> hi Deleveloper, im a big fan of ur game. Hundrets of hours on my pimax. if i may suggest Could u please remove the need of Pararell Projections ? . This is the thing that takes 30% of performance on Pimax devices to make things not to pop up in the periphal vision. I see the TV in game where the score is constatly pop up in my periphal vision when i move my head. Its really distracting , and if u could not make it go black when outside of FOV of normal headsets i would really be gratefull. Thanks !

https://www.reddit.com/r/Pimax/comments/al80ft/parallel_projection_through_the_lens_example_of/
https://www.reddit.com/r/Pimax/comments/9m3csg/do_not_forget_to_turn_off_parallel_projections/

**Comment by carrotstien** [comment]
https://www.reddit.com/r/Pimax/comments/dnabm7/disassembly_vr_now_has_pimax_support/

> this is it
`void OnPreCull()
{
        //move the camera back 2m to cater for large fov
        Matrix4x4 worldToCameraMatrix = Matrix4x4.Inverse(Matrix4x4.TRS(m_Camera.transform.position - m_Camera.transform.TransformVector(2 * Vector3.forward), m_Camera.transform.rotation, new Vector3(1, 1, -1)));
        m_Camera.cullingMatrix = m_Camera.projectionMatrix * worldToCameraMatrix;
}`

**Comment by carrotstien** [comment]
quintthemint also has a pimax and is confirming this behavior

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
