### ISSUE TITLE
[Quest][Bug] Guardian System has impact on performance

### ISSUE THREAD

**Issue by Talwar85** [ForFunLabs/ElevenPublicBugsAndAsks#28]
Hi,
when the Guardian System of the Quest shows up, than there seems to be a performance impact.
Mostly it has no impact on hitting the ball, but sometimes I miss because of it.

I cannot turn it off, because I dont want to destroy my furniture.

**Comment by carrotstien** [comment]
closing this as it's either not an issue, or not something we can do anything about :(
