### ISSUE TITLE
[suggestion]List of players in Lobby reseting

### ISSUE THREAD

**Issue by DoggyP0O** [ForFunLabs/ElevenPublicBugsAndAsks#280]
It seems that whenever someone joins or leaves the lobby (or some other reason idk, I'm just guessing this is the cause) , the list of people you can see blinks and resets. This makes it really confusing and just kinda sucks.

Maybe don't change the position every time, or just bring back refreshing the lobby to view new people.

There's also just expanding the number of people you can see at once.

**Comment by carrotstien** [comment]
lobby system updated
