### ISSUE TITLE
[issue] "OCULUS_" prefix got added to user id on oculus/rift

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#284]
earlier, on oculus/rift, my id used to be just ab050505. noticed today that a prefix ("OCULUS_") got added to it somehow. 
![121](https://user-images.githubusercontent.com/28642046/76689051-81429100-6658-11ea-98d3-33f345a11985.jpg)

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
