### ISSUE TITLE
Sticky ball 

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#290]
sticky2
https://streamable.com/zkbr4

sticky
https://streamable.com/yh9u5

not sticky
https://streamable.com/ytbu0

wasn't able to replicate yet

> StownieDazeToday at 4:13 PM
Start steamvr/game. Exit game. Reopen game, you will have sticky ball
Every time

A.A.G also gets this

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
