### ISSUE TITLE
Ball machine man

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#298]
![image](https://user-images.githubusercontent.com/234703/76880360-ee6b4780-684d-11ea-9d8a-ed2ce6703660.png)

The Poop CollectorToday at 12:44 PM
Ill test it
I opened the ball machine while i had an ongoing challenge request
when i was connected to the other user, the ball machine was still there.
I exited the match and the AI and the ball machine were there.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
