### ISSUE TITLE
Losing tracking and crashing

### ISSUE THREAD

**Issue by JoeyIsActive** [ForFunLabs/ElevenPublicBugsAndAsks#3]
Device would pop up a black screen and say tracking was lost. Try taking the headset off for a few seconds and trying again. It would just end up freezing the device and I had to reboot.

**Comment by carrotstien** [comment]
yes I had this too happen a few times. I need to see if it's perfectly repeatable...time..setting..etc..and then try to see what's going on..maybe logs will show something. 
It is very strange that "lost tracking" is something the game can cause. it should be something very low level for the platform.

**Comment by EloiStree** [comment]
Observation:
During tester with the tennis club, I observed that as soon as the Quest was around 20% of battery. It started to crash the application at some occasions.

**Comment by shonist** [comment]
Some new testing:

after playing other games i went to ETT to test this as it was the only one doing this back when i tried it.
same, went with ss 140% medium AA and high FFR and the headset tracking started to hang up and jumping into passtrough. lowered all to minimum settings (potato graphics) and solved. then came back to 140ss and medium AA and it started happening again. have to point out that framerate looks reallysmooth and prolly 72hz on this setitngs, so i may happen to think that there is some error ocurring there at high demand causing a big framedrop cpu side or something. edit: battery at 85%

**Comment by dhobi** [comment]
Just had similar effect while playing (getting owned) against AI World Class. Image froze, no more head / hand tracking. Could only restart the Quest by forcing the shutdown.
Before the complete freeze happened, I had some automatic repositioning ongoing (2-3 times) which looked like: 
1. In the middle of the game, it starts to stutter
2. The game places me in different areas with a pause of around 1-2 seconds in between
3. The 3rd or 4th placement looks correct again (where I initially was), stutter goes away.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
