### ISSUE TITLE
Can't use the beta with revive on steam

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#302]
discord user Clares#6815
tried to use an index on steam, to play an oculus version of the game through revive. They can play the legacy version, but not the revamp. 

When looking at their logs, I see the following message:

> Unable to retrieve logged in user from oculus Must call get_signature first (1971051)

**Comment by carrotstien** [comment]
to make it reach that error, you must first correct the file names:
so rename exe to 
pong_waves_vr.exe

and folder to 
pong_waves_vr_Data

**Comment by carrotstien** [comment]
get this working
```
ClaresToday at 8:56 AM
Can you give me a tip how to import the index controllers' preset into the oculus version? Not very convenient to do a custom manually since ingame controller's models are oculus touch
Perfect if it'd be possible to make the game models actually be index's
```

**Comment by carrotstien** [comment]
> 
> cabalisticToday at 11:57 AM
> Ok, so tried to debug the Revive issue today, but it just works :person_shrugging: For some reason, I can't start it from the Revive dashboard, it simply doesn't do anything, but that's a different issue than what was reported. But if I manually start it with the ReviveInjector, it works for me. Not sure what to do here, other than to recommend upgrading to the latest Revive version, if not already done...
> you can try calling it manually: ReviveInjector.exe D:\Path\To\Oculus\Eleven\Eleven.exe
>

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
