### ISSUE TITLE
[0.110.1][issue][quest] paddle position preset issue

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#308]
i had been using the second "custom" paddle position preset. yesterday i tried to switch to a preset that i had created earlier ("gfv"). it seemed to work fine. but after i quit eleven and relaunched it after some time, the selected paddle position preset was back to the second "custom" setting (the same thing happened when i tried changing to "default") . 

https://streamable.com/ebpyc

**Comment by ab050505** [comment]
looks like the paddle position preset selection change gets retained properly across eleven exit/relaunch if we select a different preset by going into "edit preset" (and clicking on the  fist symbol and selecting the preset there) and not if we select it on the main paddle settings screen itself.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
