### ISSUE TITLE
[Suggestion] Delay start of online game until text on net saying game type (ranked or unranked) goes away

### ISSUE THREAD

**Issue by barchueetadonai** [ForFunLabs/ElevenPublicBugsAndAsks#309]
If you're the receiving player in the first game of a match, it's very distracting to see the text pop up on the net saying "unranked match starting" (or something like that) while the server is already allowed to serve, rather than wait for the text to disappear (or maybe display the text on the TV instead?). It's difficult for your eyes to follow the ball over the net with the text on the net right there.

**Comment by SenninSanSensei** [comment]
Maybe some kind of transparency, or display the text on the table itself, or elsewhere. But yeah, i have a the same pb too: against good players, it's very distracting !

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
