### ISSUE TITLE
[Quest][Feature] Trail of ball in sologame --> this Purple thing

### ISSUE THREAD

**Issue by Talwar85** [ForFunLabs/ElevenPublicBugsAndAsks#31]
Is there a option to deactivate the trail in sologame?
In lobby there is no trail and it feels a bit more like table tennis without.

Could you make it a toogle?

**Comment by Rutzensior** [comment]
needs to be toggle..able..if thats a word.

**Comment by carrotstien** [comment]
removed..if some wants it back, i'll add a toggle. mostly people have asked to remove it.
