### ISSUE TITLE
[Suggestion] Be able to add someone you played with as a friend directly from Match History

### ISSUE THREAD

**Issue by barchueetadonai** [ForFunLabs/ElevenPublicBugsAndAsks#312]
Right now, it seems you have to go to User Search and type in the user in order to add them as a friend.

**Comment by biver0** [comment]
I'm not sure you're correct.  

When you go to Match History, first click on the match CARD and then you can click the opponent's name on the left and the same dialog box that you get when you click a players name from the Leaderboard comes up and you can then click Add Friend.  This is true on both the Quest and the current Steam Beta.  I didn't try it on the Oculus version.

**Comment by barchueetadonai** [comment]
> I'm not sure you're correct.
> 
> When you go to Match History, first click on the match CARD and then you can click the opponent's name on the left and the same dialog box that you get when you click a players name from the Leaderboard comes up and you can then click Add Friend. This is true on both the Quest and the current Steam Beta. I didn't try it on the Oculus version.

That feature was added in a recent update that was released after I made this post. I do find it buggy, though, as it sometimes doesn't have the Add Friend text for me.

**Comment by carrotstien** [comment]
feature added
