### ISSUE TITLE
[Suggestion] Automatically change hand in beer pong so that you're throwing with your paddle hand

### ISSUE THREAD

**Issue by barchueetadonai** [ForFunLabs/ElevenPublicBugsAndAsks#314]
Currently, your tossing hand for ping pong is used as your throwing hand for beer pong, even though it's much more likely that your paddle hand is the same as your throwing hand.

Bonus suggestion: Add in an error beep and disqualifier for crossing the table baseline with your elbow as that is a strict violation of international beer pong rules.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
