### ISSUE TITLE
[Suggestion] [Oculus-specific] If plausible, save table positioning with respect to a saved Oculus guardian so that table is positioned correctly on game startup

### ISSUE THREAD

**Issue by barchueetadonai** [ForFunLabs/ElevenPublicBugsAndAsks#315]
For those playing with limited space, it can take some time each instance of starting up the game in order to position the table to its sweet spot.

The Oculus Quest supposedly stores up to 5 unique guardians, and overwrites them as new ones are created (I'm unsure how many the Rift S saves). In order for Eleven's save state size to not arbitrarily grow by saving data on a boundless number of guardians (even as those guardians are overwritten on the Oculus), I suppose that storage data mapping table positioning to a specific guardian state be deleted if that guardian is no longer found in the Oculus's data.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
