### ISSUE TITLE
Eleven not loading 

### ISSUE THREAD

**Issue by takaloo1234** [ForFunLabs/ElevenPublicBugsAndAsks#317]
This game won’t load on my oculus quest it starts to load then it chucks me back to my library please help

**Comment by carrotstien** [comment]
Hello Takaloo1234. Have you been switched to version 15 of the firmware? 

Can you try to uninstall, reboot headset, reinstall, and try to open it then? I've had it crash a few time as well, even older builds. 

If this doesn't work, I'll be happy to troubleshoot further. 

I'm faster to find on the discord:

me:carrotstien
discord:https://discord.gg/v8bwdwf

**Comment by carrotstien** [comment]
from another user

> --Funfire--Today at 7:49 PM
> I’m quite mad about this game rn
> I download it
> And open it up
> With a play space that meets the 6.5ft by 6.5ft playspace
> And it just crashes on me
> Any reason to that?
> I’m on quest btw
> carrotstienToday at 7:52 PM
> hi @--Funfire--
> can you check yuor firmware version?
> I've see a smattering of people complain lately, and it's coinciding with v15. but I haven't deployed since 3/13.
> --Funfire--Today at 7:54 PM
> Yea I’m on v15
> carrotstienToday at 7:54 PM
> Can you try to uninstall, reboot headset, and then reinstall?
> and let me know if that fixes it
> --Funfire--Today at 7:54 PM
> Ok
> carrotstienToday at 7:54 PM
> i think oculus firmware is doing something bad :frowning:




> --Funfire--Today at 7:57 PM
It’s just stuck on uninstalling now
carrotstienToday at 7:57 PM
damn
yea that's def firmware :frowning:
ugh

**Comment by carrotstien** [comment]
and this one
https://www.reddit.com/r/OculusQuest/comments/fr9wkt/eleven_table_tennis_not_able_to_start/

> Eleven Table Tennis not able to start
Question/Support
I've just bought this game and I've not been able to run it once. It crashes all the time on start. I have restarted Quest and made sure that guardian area is big enough. Any idea?

**Comment by carrotstien** [comment]
and this one from discord user elad808

> My Oculus Quest upgraded to version 15 of the OS and my Eleven Table Tennis crashed.  I would not start up anymore.  I tried to uninstall/reinstall, but it's stuck "uninstalling".  Do you know how to fix this?


> @carrotstien I did end up having to factory reset.  I used sidequest to backup important game saves and other I just let go.  Eleven table tennis has been running fine so far.  One thing I didn’t do this time is switch to the new universal UI since that’s what kicked be out last when I was switching in and out of the app.

**Comment by carrotstien** [comment]
this should be resolved
