### ISSUE TITLE
Log out Ball speed/spin speed

### ISSUE THREAD

**Issue by barefootford** [ForFunLabs/ElevenPublicBugsAndAsks#318]
I've been working on my fundamentals and attempting to generate more spin and increase speed. It would be cool when playing single player modes to be able to have a display off to the side of the table to show your most recent shot's speed and spin (RPM?).

This would be a cool way to verify better form generates better offense.

Thanks for the incredible game ⚡️

**Comment by dukeoflegs** [comment]
Closing, spin and speed shown on TV.
