### ISSUE TITLE
minor language related issues

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#320]
when we switch to another language, and start an sp match, after a point is completed, the "received a point due to reason" bit in the message on the tv is still in english (though the rest of it is in the selected language). also after a match is completed, the "restart match" button on the left is still in english. and when we switch environments (studio/chalet), the environment descriptions ("a quiet studio" etc.) that are shown are also still in english.

**Comment by DavidJelinek** [comment]
I have found other missing translations.
![ETT_1](https://user-images.githubusercontent.com/24259213/78843363-e3e23f00-7a02-11ea-8a24-630786da8810.jpg)
![ETT_2](https://user-images.githubusercontent.com/24259213/78843365-e5136c00-7a02-11ea-90cc-6731ae47f05b.jpg)
![ETT_3](https://user-images.githubusercontent.com/24259213/78843366-e5136c00-7a02-11ea-9e8f-b615273c6168.jpg)
![ETT_4](https://user-images.githubusercontent.com/24259213/78843367-e5ac0280-7a02-11ea-8332-bf5777b8f5eb.jpg)
![ETT_5](https://user-images.githubusercontent.com/24259213/78843368-e5ac0280-7a02-11ea-89b5-cdcd8656f46b.jpg)
![ETT_6](https://user-images.githubusercontent.com/24259213/78843369-e6449900-7a02-11ea-86c7-d755d597d2c2.jpg)
![ETT_7](https://user-images.githubusercontent.com/24259213/78843370-e6449900-7a02-11ea-862d-bea5c4b8dacf.jpg)

**Comment by DavidJelinek** [comment]
![ETT_8](https://user-images.githubusercontent.com/24259213/79053598-ec26be00-7c3e-11ea-9987-d0c29eb3ed8c.jpg)

**Comment by DavidJelinek** [comment]
![ETT_9](https://user-images.githubusercontent.com/24259213/79110749-63616c80-7d7b-11ea-91a3-c29b45e844c0.jpg)

**Comment by DavidJelinek** [comment]
![ETT_10](https://user-images.githubusercontent.com/24259213/79694717-688a5400-8272-11ea-96be-2d8519a91b06.jpg)
These keys are translated in Localization table.

**Comment by GeneralFailure-ch** [comment]
![grafik](https://user-images.githubusercontent.com/52096743/80673316-492fca00-8aaf-11ea-927d-3eef3e6f5027.png)

**Comment by GeneralFailure-ch** [comment]
![grafik](https://user-images.githubusercontent.com/52096743/80673532-d2470100-8aaf-11ea-9e9f-0e67803f2d36.png)

**Comment by GeneralFailure-ch** [comment]
![grafik](https://user-images.githubusercontent.com/52096743/82576298-fadf8980-9b89-11ea-916e-bd61a796c153.png)

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
