### ISSUE TITLE
[Suggestion] Show ELO of opponent during match.

### ISSUE THREAD

**Issue by Cristy94** [ForFunLabs/ElevenPublicBugsAndAsks#321]
You can currently see the ELO of a player in lobby, but as soon as you join a room there is no way to see opponent ELO.

I think ELO could be shown on TV below player names.

It would be useful to also see it on match-end screen where you see your ELO delta. Either just show the opponent ELO or also his old ELO, delta and new ELO.

**Comment by DavidJelinek** [comment]
I suggest show ELO, when choose type of game ranked/unranked.

**Comment by dukeoflegs** [comment]
Closing, UI updated
