### ISSUE TITLE
Racket Switches Hands After Headset Off and Back On

### ISSUE THREAD

**Issue by biver0** [ForFunLabs/ElevenPublicBugsAndAsks#322]
I'm having a problem where when I take off the headset and the put it back on to continue playing, my racket is in my left (wrong) hand.  I click on the right (correct) hand in the menu and everything is fine.  Steam, Rift, Beta, --Best. Game. Ever.

**Comment by carrotstien** [comment]
is this still happening? I've pushed a few updates to try to fix it

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
