### ISSUE TITLE
Unwanted random ball acceleration on serve, either when thrown-up or hit.

### ISSUE THREAD

**Issue by biver0** [ForFunLabs/ElevenPublicBugsAndAsks#323]
An Issue I have, randomly from time to time, is that there is a sudden acceleration to the ball.  It can happen then I throw the ball up to serve or when I serve and have too much power that I didn't give it.  The throwing up of the ball feels like a serve ball boost assistant (can't remember in this moment what it's called) in settings, but it's off.  I'm not as confident to say that I've felt this in gameplay in a way that's as obvious.

**Comment by Llamalland** [comment]
I get this sporadically too.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
