### ISSUE TITLE
Can't change paddle position preset values

### ISSUE THREAD

**Issue by esFiner** [ForFunLabs/ElevenPublicBugsAndAsks#325]
In the Paddle Position menu, once you select VR-PADDLE-R you won't be able to change any of the other presets until you leave the menu.

On version 0.117.3.

I don't have a paddle adapter, so my current present is one of mine for the standard Rift S controller. I toss the ball with my left hand, with paddle in my right hand.

1. From the main menu, goto _settings_ - _paddle settings_ - _paddle position_
2. Selecting any preset other than _VR-PADDLE-R_ and check you can change position by pressing the grip button and moving the paddle hand.
3. Now, select _VR-PADDLE-R_. Values for this preset are hardcoded as intended; can't be changed with the grip button.
4. Select any of the other presets and try to change them again. The overlayed controller won't move, as well as the displayed values.
5. Leave the _paddle position_ menu.
6. Return to the _paddle position_ menu.
7. You can now change the preset values.

**Comment by carrotstien** [comment]
fixed in upcoming patch

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
