### ISSUE TITLE
[issue] beer pong leaderboard not updating immediately

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#330]
in beer pong, the leaderboard doesn't seem to get updated immediately. completed the first round. leaderboard displayed empty. completed the second round. leaderboard displayed my score from the previous round even though my score in this round was higher. the higher score appeared in the leaderboard after the next round (where my score was lower). and so on. basically displays a higher score at the end of the next round.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
