### ISSUE TITLE
[issue] strange notifications behavior

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#331]
i receive a notification. try to check it. sometimes there's nothing there. at other times, it says match request received 11 hours ago (even though i'd seen the player in the lobby just a few minutes ago). i accept it and i'm in the match.
https://streamable.com/hmg5ci

**Comment by ab050505** [comment]
![image](https://user-images.githubusercontent.com/28642046/79688511-632a0b00-826c-11ea-8c8a-b78e0ab2bafe.png)

(says "5 hours ago" on the left and "11 hours ago" on the right)

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
