### ISSUE TITLE
Defaulted set because of Time Violation doesn't end match

### ISSUE THREAD

**Issue by Taramoc** [ForFunLabs/ElevenPublicBugsAndAsks#338]
I was playing a ranked match, and the controller of my opponent died, so he went to put another battery in. He got timed out for all the violations, so I won the point first then the set. I had already won the first set, but the game didn't give me the match. Instead queued up the third set, even if I had already won two.

I had two dots on the TV to the side, the third set was queued up, I clicked on the button to look at the menu, and I saw my two sets as 11-8, 9-6.

**Comment by dukeoflegs** [comment]
Closing
