### ISSUE TITLE
multiple accounts per headset

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#339]
a few people have asked..but basically:

I don't know if someone even speak about that, but in our family we are 4 to play to eleven with only 1 Quest.
It could be nice to have several account with his own ranking.

**Comment by Ken-Gilb** [comment]
Love this idea. I have the same problem. It's too bad the quest doesn't support multiple profiles out of the gate.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
