### ISSUE TITLE
[Quest][Bug] Different bouncing on differant surfaces

### ISSUE THREAD

**Issue by Talwar85** [ForFunLabs/ElevenPublicBugsAndAsks#34]
do the items have different surfaces and change the bounce of the ball? 
Seems like the ball is bouncing always the same

Talwar85_
in the room
more the floor and the table

carrotstien_
ah the studio
yea it's all stone  now
but imma fix that

**Comment by Llamalland** [comment]
It'd be a cool gimmick to have different surfaces to the table with different proporties, like rubber for ridiculous spin effect, something softer which absorbs some of the power etc. Same for call.

**Comment by carrotstien** [comment]
should be fixed as of 0.9.3
