### ISSUE TITLE
Multiple bugs I have taken time to find.

### ISSUE THREAD

**Issue by CodyS12345** [ForFunLabs/ElevenPublicBugsAndAsks#340]
First bug- The ping compensation glitch. If you turn your ping compensation to 40, if you do it within like 1.5 seconds you can hit the ball up and them slam it. If you try it you would know what I mean.
Second bug- Crashing with bots do to AI reduce mistake/very fast legendary moves that some headsets/computers cant handle.
Third bug- If you grab the ball right before the match starts on multiplayer, it will glitch if its your serve first and the ball would be stuck in the air unable to be grabbed.
Fourth "bug"- Unable to get rank on won ranked games. I had it show up as 305-0=305. Idk how that happens. Oh also sometimes the thing doesn't show up at all, and usually after if you go to the lobby for multiplayer it will take forever to load.
Fifth bug- multiple players joining your game at once and them all colliding with eachother and glitching and its just a mess.

There are probably other bugs out there, but these are some that I mentioned (I don't know if some of these are fixed with the latest update)

**Comment by carrotstien** [comment]
hi Cody .If you have time to chat in more detail i'd appreciate it. Here is the discord:
https://tiny.cc/vr11

i'm not sure what you mean by the first bug. If you hit the ball up..and then slam it down - during a point..you should lose that point? Are you saying you don't lose the point??

i'm not sure what you mean by bug 2

the others i either know of , or will look into

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
