### ISSUE TITLE
Flat surface orientation

### ISSUE THREAD

**Issue by Llamalland** [ForFunLabs/ElevenPublicBugsAndAsks#343]
I have an interesting suggestion, related to #peripherals but not limited to it. After precisely making sure that when my adaptor was level, my in-game bat was level, I saved that orientation, but the next time I restarted the computer and went into ETT, it was just a few degrees off. 

Obviously oculus doesn't perfectly relay orientation or position, so I think it would be cool if you could, after saving an orientation, lay the controller/adaptor on a flat surface in some specific way, press something to say "the controller is on a flat surface" and then any time you feel like making sure the orientation is right, click a similar button to say "my controller is lying in the same way on a flat surface" and then ETT can rotate the orientation so it's correct relative to that. Obviously it can only fix 2 degrees of freedom (unless you can also ensure it's pointing in the right direction, then you get 3) but the other 3 degrees of freedom can just so that a centre of gravity or something is fixed.

Possibly with options for "my controller is on a flat surface and in-game rubbers should be parallel to the floor" or something like that.

**Comment by dukeoflegs** [comment]
Closing
