### ISSUE TITLE
LIV / Mixed Reality support

### ISSUE THREAD

**Issue by PatTheHyruler** [ForFunLabs/ElevenPublicBugsAndAsks#344]
Title should be pretty self-explanatory, I'd love to be able to set up a virtual camera and film myself playing table tennis in mixed reality.

Not sure if the PC version supports this already because I don't have Eleven Table Tennis VR on PC, but it's not in the LIV supported apps list and regardless, I'd like to see the feature on Quest.

**Comment by dukeoflegs** [comment]
Support enabled
