### ISSUE TITLE
UI/menu changes

### ISSUE THREAD

**Issue by Llamalland** [ForFunLabs/ElevenPublicBugsAndAsks#349]
I think a couple of menu items could be streamlined a lot. To change environment you need to press menu, click on the mountain, click on a name and click go. 

I think at least until there are too many envs to fit a launch button and a description for each on to one page, one of those clicks could be eliminated.

Same goes for minigames.
Also when you "mouse over" the environments button, it still shows the version number and not "Environments", same with unity settings.

I think also when you click on one of the 4 big icons (SP, MP, minigames, tutorial), the menu that opens that replaces that horizontal strip should instead appear below it - so when you click on multiplayer, you should still see those 4 big icons, but a horizontal strip with profile, lobby, leaderboard etc should appear below that. There's room for it ;)

While I'm on that topic, I don't think the strip for multiplayer having 6 items, only 4 of which are visible is a good idea, many people don't know the 2 hidden items exist at all.

**Comment by dukeoflegs** [comment]
Closing, UI update
