### ISSUE TITLE
[issue] ball toss not working in serve practice mini game sometimes

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#360]
(latest release/quest)
steps to reproduce:
1. launch eleven.
2. start a single player game and end it.
3. start serve practice mini game. ball toss does not work.
4. start another single player game and end it.
5. start serve practice mini game again. ball toss works.

**Comment by ab050505** [comment]
(logs submitted in-game about 15 minutes ago)

**Comment by carrotstien** [comment]
fix inbound

**Comment by ab050505** [comment]
verified that this issue is not occurring in the latest release.
