### ISSUE TITLE
[Quest] Game not recognizing lost ball

### ISSUE THREAD

**Issue by XekriRedmane** [ForFunLabs/ElevenPublicBugsAndAsks#361]
After today's update (1.361) when playing online, the game seems to have a bit of difficulty recognizing that a point has been won. I found myself having to go to Reset Ball many times during the match.

**Comment by carrotstien** [comment]
please let me know if that happens again. I think i know what happened, and
i just restarted the server, so everyone should be on teh same version.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
