### ISSUE TITLE
Spectate Camera Suggestion

### ISSUE THREAD

**Issue by g4vg4v** [ForFunLabs/ElevenPublicBugsAndAsks#365]
For the desktop view, when viewing in first person before enabling spectate camera, have an option to raise the fov higher as the fov as is now is very low and claustraphobic.

For the spectate camera, have an option to view the table from the perspective of a real life tournemant, where it is behind one player, high up and angle down to the table. Similar to this image ive grabbed from google: 
![image](https://user-images.githubusercontent.com/67441609/85796653-3396f380-b732-11ea-998f-b1111265419b.png)

this keeps it at the centre of the screen where you can see all the action without a lot of adjustment for the eyes/head. with the default map however, it might be an issue due to how small the enviroment is, but if you have this option as a sepearte setting, it could hide the walls/ceiling/objects to see the players and the table for one angle or the other.

**Comment by carrotstien** [comment]
you can already do close enough, but once i add in game FOV adjustment, you can do it exactly

![image](https://user-images.githubusercontent.com/234703/85799364-18fe5380-b70d-11ea-95b3-2588a149cecf.png)

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
