### ISSUE TITLE
Tournement Enviroment

### ISSUE THREAD

**Issue by g4vg4v** [ForFunLabs/ElevenPublicBugsAndAsks#366]
have an enviroment similar to how a tournment would look. this keeps the map clean of objects for better performance, few distractions on the background, and have a nice enviroment for spectate. something similar to this image ive pulled from google: 
![image](https://user-images.githubusercontent.com/67441609/85796587-17935200-b732-11ea-93d7-10a188068ec1.png)

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
