### ISSUE TITLE
[possible minor issue] opponent match type selection not visible immediately after environment switch

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#367]
received an invitation to play from a player who happened to be in chalet (while i was in studio). after accepting, my environment too changed to chalet. when i brought up the match type selection dialog, it looked like the opponent hadn't selected a type yet. i waited for the other player to select a match type but they gestured that they had already done so. when i  selected ranked, a ranked match started (as indicated by the message at the net). so looks like the opponent's match type selection had not been visible on my side that first time (seemed to work fine for later matches).

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
