### ISSUE TITLE
Ballmaschine produziert keine Bälle

### ISSUE THREAD

**Issue by BOBWOP** [ForFunLabs/ElevenPublicBugsAndAsks#370]
Plattform Quest, was tun?

**Comment by carrotstien** [comment]
can you try to reset the ball machine?

https://youtu.be/gLOfpF_GZK8

**Comment by carrotstien** [comment]
if that doesn't work....are you able to toss the ball and hit it in other modes? If not, please go to the last setting option, and disable any 'special tracking' stuff you may have enabled

![image](https://user-images.githubusercontent.com/234703/87250066-a7264980-c430-11ea-9f20-34a255c18bdd.png)

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
