### ISSUE TITLE
In game key lock preventing menu close post ai serve

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#371]
**ankitkvToday** at 11:12 PM
Recently I've been playing single player with the world class bot as practice. If I get a MP request notification during a game and I check it after the ball goes out of play, the bot keeps playing (if it's its turn to serve) and I lose a point because the ball comes out of nowhere while the notifications screen is open. But even if I realize the bot is playing and I want to close the menu, I am unable to close the menu no matter how many times I press A, and can only successfully do it after the ball goes out of play because I miss the oncoming serve (or it might just be until the serve is launched)
There seem to be 2 bugs here:
1) (maybe not a bug but close) Ideally the bot shouldn't start the serve if I have a menu open
2) I should be able to close the menu before the bot's serve finishes

**carrotstien** Today at 11:16 PM
ah...i think the bug is... when point is active, you can't press any buttons
in single player mode at least
but that is clashing with...the ai is serving when the menu is open

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
