### ISSUE TITLE
game doesn't start from steam vr home when owned on oculus home

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#377]
HenrystickminToday at 10:08 AM
hello i just got the game and when I tried to launch the game it shows very quickly the language opens far below me and then goes black screen
when I check my pc it shows not responding
this is on the rift 2
carrotstienToday at 10:10 AM
hmm, could be a few things. 
when you put on the riftS headset, do you see the oculus home environment, or the steamvr environment?
HenrystickminToday at 10:13 AM
i launch it from steam vr home
it works fine from occulus home
is it cross platform between steam and oculus store?
carrotstienToday at 10:15 AM
yes
oh maybe it's doing something funky there
where do you own it?
oculus home or steam?
i'm not sure why it wouldn't be working form steam vr home unfortunately ... i guess for now just launch it from the p c from oculus home
i'll try to look into what could be happening
but if you are still able to play fine...just slight inconvenienced by how to start it, i'd rather concentrate on more pressing matters
if that's ok with you :slight_smile:

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
