### ISSUE TITLE
Racket Grip Setting Suggestions & Other Random Thoughts

### ISSUE THREAD

**Issue by jastoneii** [ForFunLabs/ElevenPublicBugsAndAsks#378]
Hi,

I've been playing Eleven VR for just over 1 month now on a Quest.  I've been trying to optimize the racket grip settings as I play only with the Quest hand controls.  Since I try to play with both hands (at different times), I like that I can save different settings.  

Many racket sport players use slightly different grips for their forehand vs their backhand.  Because I use the Quest hand controls, I cannot shift my hand  the way I would with a real racket.  So, can a future update allow different customized setting for backhand and forehand?  Also, current grip setting is achieved visually to set the two different combinations of X Y Z parameters.  In an effort to find the optimal settings, I will try new grip options. However, if I don't like a new grip compared to an old one its very hard to get back to the prior settings visually.  (It may be that I'm 60 y.o. and my hands are not the most steady.) It would be very helpful if a user could select an individual axis parameter and hit a button to increase the value or another button to decrease it.  This would allow users to test subtle grip changes easily.

Other thoughts...  

I have noticed that when someone invites me to play, I cannot see their connection strength.  I find it very frustrating to play people with less than 3 bars as they often seem jittery. Could you display their connection strength along with their invite?

Is there a spot to find more information about the different settings as the tutorial only gives the basics?  I would like to understand more about the toss setting, the spin, bounciness and throw coefficients.

Finally, about once every other day, I get a warning about a serve toss and before I can reserve, I get hit with a service fault.  Which is problem #1.  When the service fault occurs on my second of two serves, often my opponent does not have a ball and neither do I.  We both click on lost ball but that only works about half the time.  Perhaps allow a reverse point option, if both players agree to it?

When I last played competitively, rackets did not exist that enabled the amount of spin that I seen some players achieving; however, I'm enjoying the game immensely.

**Comment by carrotstien** [comment]
hello @jastoneii... you play the game completely with no controllers?? (i didn't even know this was remotely possible). or when you say "quest hand controls" you mean "quest controllers"? 

yes we need to add local/locked axis manipulation just as you described. 

regarding being able to see their connection strength: it's not a strength, that's just proximity. The jitteryness I need to look into (maybe i can add smoothing or something). You can have a completely non jittery connection with 0 bars, or a jittery one with 5. 
So the only things the bars tell you are the approximate latency..and i hope with an update in the near future, latency no longer is a problem. 

Yes there is an eleven wiki, but it needs a loooot of work on it. https://eleven-vr.fandom.com/wiki/Eleven-VR_Wiki

regarding the serve toss..yea that sounds like a bug. I'll fix it. 

i'm faster to reach via chat:
via discord chat: https://tiny.cc/vr11 (i'm carrotstien there)
via facebook chat: www.facebook.com/ElevenVR

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
