### ISSUE TITLE
[Quest][Feature] Paddle size seems a bit small

### ISSUE THREAD

**Issue by Talwar85** [ForFunLabs/ElevenPublicBugsAndAsks#38]
Could there be a slider to configurate the paddle size? Or choose from 3 different sizes.

**Comment by carrotstien** [comment]
apparently ITTF rules don't specify a paddle size. Considering tracking irregularities, we might increase it back to the size it was in the previous version of the game (which apparently was 20% bigger)

but maybe there will be options for more realistic sized paddles /shrug

**Comment by carrotstien** [comment]
updated
