### ISSUE TITLE
Can't create a room

### ISSUE THREAD

**Issue by jc3113** [ForFunLabs/ElevenPublicBugsAndAsks#382]
Hi,
I have a Quest and a Quest 2, but I have only one account,
I saw videos on youtube said that I can play with my friend when I have two devices but on account.
My network is fine (both connected with same 5G wifi) , I can play with other players around the world,
but when I want to play it with my friend, I pressed "room" tag,
the screen just kept showing the loading icon (a spinning circle) and nothing further.
Could anybody help me to solve this problem?
Or is there any other way to play with friends with only one Oculus account?

Thanks!

**Comment by carrotstien** [comment]
Hi. Why are you doing something different to play with your friend than you
do to play with anyone else :)

The second instance of the same account just appears as the same name but
an appended "_guest"

**Comment by jc3113** [comment]
Oh I get it! The name of the other device will show up on the top of the list, all I need to do is to invite him to join. I thought I need to create a room and get a room code for this. Thanks a lot!
