### ISSUE TITLE
[0.171.0][quest] stuck at 'connecting'

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#387]
accepted an invitation from a player. the session got stuck at "connecting". i could see in the side panel that the other player's ping was fluctuating from 90 to 800ms. there seemed to be no way for me to close the connection and return to lobby. after waiting for a few minutes, i exited eleven and relaunched it.

**Comment by carrotstien** [comment]
did you press the send logs button?

**Comment by ab050505** [comment]
afraid not (thought of it but since the other player had not yet joined, seemed like it might not be of much use. will click next time it happens)

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
