### ISSUE TITLE
[0.171.0][quest] ai invisible in sp

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#388]
after i relaunched the game after running into the following issue, the ai was not visible in sp (it came back after exiting eleven and relaunching again):
https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/387

https://drive.google.com/file/d/1iDoby_H3E_o6rOoaEyZIBJUFVsdiWYbZ/view?usp=sharing
(clicked "send logs" as well)

something similar seems to have been reported on discord a few months ago:
![image](https://user-images.githubusercontent.com/28642046/101194103-8aaad800-3683-11eb-9d83-eed6c57b86ab.png)

**Comment by carrotstien** [comment]
Yea i think I have sorted out the avatar-is-grey bug, but not the avatar
doesn't load at all bug yet. (it's also random)

**Comment by MrSquidy321** [comment]
Same, the first time I played, o thought the AI was meant to be invisible

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
