### ISSUE TITLE
[Quest][Bug] Win 10 to 11 vs AI Easy 

### ISSUE THREAD

**Issue by Talwar85** [ForFunLabs/ElevenPublicBugsAndAsks#39]
I won vs AI easy 10 to 11. 
This shouldnt be possible if I understood the rules correctly. 

Rules from http://www.pongworld.com/table-tennis-sport/rules
"For each game, the first player to reach 11 points wins that game, however a game must be won by at least a two point margin."

**Comment by carrotstien** [comment]
should be fixed as of 0.5.2
