### ISSUE TITLE
Table tennis paddle Add Appearance 

### ISSUE THREAD

**Issue by hojin9** [ForFunLabs/ElevenPublicBugsAndAsks#391]
Hello!
Table tennis paddle Add Appearance 
penholder grip Additional requesting
The image is shown in the link below.

https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F993DDA485A9D39E225

https://dic.kumsung.co.kr/upfiles/editor/201508/b69so6jq6qc3gc2jkqq46g1ili.jpg

**Comment by dukeoflegs** [comment]
Closing,
