### ISSUE TITLE
Double 'pop' when ball is hit associated with velocity errors after collision

### ISSUE THREAD

**Issue by jswelling** [ForFunLabs/ElevenPublicBugsAndAsks#394]
Description: sometimes when the paddle strikes the ball, the 'pop' sound happens twice in rapid succession.  This seems to be associated with errors in the post-collision velocity- typically the ball seems to be moving too fast, and/or the rebound angle seems off.

When does this occur?: I'm running on an Oculus 1 in single-player mode against the AI.  I have a pretty low level of skill so I'm not doing anything tricky.

I'm pretty sure this is unphysical.  Since the ball should leave the paddle at the same speed it arrived in the center of mass coordinate system, the paddle should almost never be able to catch up to the ball and hit it again before it is away.  My guess is that you get ball and paddle data at time intervals and are calculating the collisions at those times rather than interpolating the ball and/or paddle positions iteratively until you can estimate the time of the single collision.  If you're not already doing it I'd propose iterating to estimate a single moment of collision somewhere between the time samples.  

I'm a computational physicist with experience in discrete event simulation and VR, and I'd love to talk about the collision dynamics if there is a way to do so.  I feel like simulation problems are limiting my ability to beat the damn AI, for example because trying to slam the ball tends to trigger this error!

**Comment by carrotstien** [comment]
Hi,

I'm ready for some physics talk, but it'd be easier over chat (discord is
best:)

  via discord chat: https://tiny.cc/vr11 (i'm carrotstien there)
via facebook chat: www.facebook.com/ElevenVR

-Roman

**Comment by jswelling** [comment]
Discord will do- see you there.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
