### ISSUE TITLE
[Issue] Avatar is always Cat mask on multiplayer (oculus quest2)

### ISSUE THREAD

**Issue by peterbrown05** [ForFunLabs/ElevenPublicBugsAndAsks#395]
I have configured a custom avatar in my profile
 If I play single player, the computer bot has my avatar.

However whenever I play multi-player i appear as the cat mask. (I've asked the people im playing against what they see and they confirmed i too was a cat), and after many games the opposition always has the cat mask too. 

Ie it seems that no matter what is configured, all players have the cat mask for multi-player

I'm running on oculus quest2 natively

**Comment by carrotstien** [comment]
Yep, thanks. This is fixed in the coming patch :)

for right meow, everyone is cat :P

-Roman

**Comment by bluEEil** [comment]
I don't know if it's the same issue but for me when I enter the game I'm a cat, but if I open the avatar setting I see the scary rabbit is already selected but after viewing this setting my opponents see me as scary rabbit instead of cat.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
