### ISSUE TITLE
Questions about Game Matching

### ISSUE THREAD

**Issue by INSPRT** [ForFunLabs/ElevenPublicBugsAndAsks#396]
Please read it considering that i'm from non-English country. and i don't know if I can ask a question here.

Anyway, here's my question. i don't like the current invitation method. The current "invitation" format is too uncomfortable and negative for fair ELO calculation. Therefore, You guys are have any plans to improve the friendly/rank matches to the auto-matching method according to the ELO? 

If you have a plan, when do you expect it to be completed?

**Comment by carrotstien** [comment]
yes, it is currently in beta testing. So hopefully today/tomorrow :)

**Comment by INSPRT** [comment]
> yes, it is currently in beta testing. So hopefully today/tomorrow :)

Awesome! Thanks for the answer. I have one more question.
Can I choose to meet only green pings? I think this is most necessary.

**Comment by carrotstien** [comment]
There are 4 parameters used to weight how good a match is:

ELO closeness
geographic proximity
match history
waiting time


As people play and provide feedback, I can tweek these coefficients.
