### ISSUE TITLE
Eleven voice takes over my quest 2 mic

### ISSUE THREAD

**Issue by SteveLobdell** [ForFunLabs/ElevenPublicBugsAndAsks#397]
This isn't so bad but it can be annoying, but when I play Eleven It screws with my Oculus Quest voice party.  People can't hear me or I can't hear them.  I also noticed that I tried to use a voice command to shut down my quest 2 while Eleven was running and it said my mic was in use or something similar.

Again, not sure if this is on your side or just a limitation of the quest 2.  Thanks

Steve

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
