### ISSUE TITLE
Bug: ball passes through black side of paddle on serve, consistently over a game session.

### ISSUE THREAD

**Issue by jswelling** [ForFunLabs/ElevenPublicBugsAndAsks#398]
I experienced this on an Oculus Quest 1 and sent a log from the in-game button at about 7:30PM Eastern on 1/15/2021 EST with a problem type of 'physics'.  I've seen this intermittently before, but this time it was solid and repeatable.  Ultimately I had to restart the game to clear it.  It happened from the first serve of the game, which was single-player.

It's not an acceleration or motion-tracking bug, because I was able to hold the paddle still and drop the ball on it from the other controller from above with no significant motion of any object except the ball.  When I dropped the ball on the black side of the paddle it would visibly pass right through and fall until it hit the floor.  When I turned the paddle over and dropped the ball on the red side, it would bounce off the paddle as expected.

I could serve the ball using the red side of the paddle, and thereafter play seemed normal.  I consistently could not serve with the black side; the ball just passed through.

I've seen this intermittently in play at other times.  For example, I'll try to serve, the ball seems to pass through the black face, I'll stop the paddle and accidentally move it backwards, and the red face with strike the ball and send it backward.  This was never consistent, and the following attempt or second following attempt the behavior would be normal.  On this particular game the condition was stuck and even persisted through several normal volleys served by the robot.  After I exited the game and restarted, I did not see the bug on any of my serves for the next 11 games.  This is rare; I'd expect at least a few instances in the normal course of 11 games.

**Comment by SouthbayTT** [comment]
I've had this exact same issue several times. You never know when it will start doing it and usually dont notice til a game is starting. 

Had to use the other side of the paddle for the entire game then reboot to clear.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
