### ISSUE TITLE
Invisible Opponent - see the ball only

### ISSUE THREAD

**Issue by SouthbayTT** [ForFunLabs/ElevenPublicBugsAndAsks#400]
Today at 1154am I was playing Eleven TT against HECTORHIGUERAREALTOR on my OQ2 and I could not see him nor his paddle for the entire game. This is my page that shows the game in my history. https://www.elevenvr.net/eleven/184576

Its probably notable that I had removed my headset to clean it off right before the game, and I put it on and clicked "Matched" thinking he was out of view for a minute and would return, but then he clicked "Matched" and the game started, and the ball just started moving. I could not see him at all for the entire match. I had us both muted so I dont know if sound was working or not.

I also did the long-press of the Oculus button to redraw the room several times, but it didn't help, he was still invisible and remained so for the entire match. 

Fortunately I still won the game, but it was definitely much more challenging with an invisible opponent.

I rebooted my OQ2 and things returned to normal.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
