### ISSUE TITLE
Stuck in Offline status

### ISSUE THREAD

**Issue by slayinturds** [ForFunLabs/ElevenPublicBugsAndAsks#409]
Starting the game, my status is offline. Friend list empty, lobby empty. My username shows as "Player" no sure what the issue is or how to correct this without losing my profile? Any help much appreciated. First time posting here, big fan of the game.

**Comment by carrotstien** [comment]
Hi, I'm in bed already, but stop by the discord tomorrow and find me
(carrotstien)

You can try toggling tcp mode within the game's debug settings (tree icon -
network debug

**Comment by slayinturds** [comment]
Hi!
That worked like a charm!! I am back in biznass! Thank you!!!!
Madison

**Comment by dukeoflegs** [comment]
Closing, no longer an issue
