### ISSUE TITLE
problems with double vision of the ball

### ISSUE THREAD

**Issue by luisdelucas11** [ForFunLabs/ElevenPublicBugsAndAsks#410]
Hello.
I've had problems with the game for 3 days. When playing against online opponents, when I hit the ball, I see it repeated, and one first and one later with delay, and it makes me dizzy. When the opponent hits the ball, or I play out of line against the machine it doesn't happen to me. I've been playing the game for 2 months, and everything was perfect so far. I would like to know how to solve it. Thank you so much

hola.
desde hace 3 dias tengo problemas con el juego. Al jugar contra oponentes online, cuando golpeo yo la pelota, la veo repetida, yna primero y otra despues con retardo, y marea mucho. Cuando golpea la pelota el oponente, o juego fuera de linea contra la maquina no me pasa. Llevo jugando 2 meses al juego, y todo era oerfecto hasta ahora. Me gustaria saber como resolverlo. muchas gracias

**Comment by carrotstien** [comment]
Hello,

It sounds like you enabled ping ball in the menu and didn't notice.
Check out this video explaining what it is and how to enable (and thus
disable it)
https://www.youtube.com/watch?v=nkZu9MO8WMg

-Roman

**Comment by dukeoflegs** [comment]
Closing, no longer an issue
