### ISSUE TITLE
(Feature Request): Use thumb joystick for scrolling/PgUp/PgDn when browsing scrolling lists (ie lobby, friends list etc)

### ISSUE THREAD

**Issue by SouthbayTT2** [ForFunLabs/ElevenPublicBugsAndAsks#415]
For every scrolling multi-page list (such as the lobby, friends list, match requests, friend requests etc): It would save a lot of time and make the game get started faster if you didnt have to aim at the tiny "scroll up" and "scroll down" buttons to see the rest of the list. If we could just use **either thumb joystick to scroll through the list**, we could arrive at what we're looking for much faster and get in more games per day.
Thank you!

**Comment by dukeoflegs** [comment]
Closing, no longer an issue
