### ISSUE TITLE
[suggestions]  more intuitive menu / option selection

### ISSUE THREAD

**Issue by fdokic** [ForFunLabs/ElevenPublicBugsAndAsks#419]
it is very unnatural and hard to set parameters (e.g. AI auto target location & variance). A natural control thereof with the occulus controllers would make things much easier. E.g. place a virtual "puck" where the target should be & control its variance radius through the grip & drag control. Similar things could be set for e.g. ball machine and others

**Comment by dukeoflegs** [comment]
Closing, new UI
