### ISSUE TITLE
[issue][preview] received an mp challenge though "none" selected for mp lobby

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#423]
installed preview, selected "none" when prompted regarding mp lobby setting (ie., did not want to receive challenges from anybody), received a challenge from somebody (forgot the name, elo around 2300) a short time later, did not accept, sent logs (mp/performance)(double-checked the mp lobby setting and it was still set to "none")
(this was around three hours ago)

**Comment by ab050505** [comment]
(also on the day of installing the preview, my starting elo was shown as 1500 and the matches that i played that day are not visible in my match history on elevenvr.net (there were no problems with my internet connectivity). the next day, my elo was showing properly in game and the matches that i played are present in my match history. this type of issue used to occur a fair bit in the live version as well for me until a couple of months or so ago but hasn't occurred again since.)

**Comment by dukeoflegs** [comment]
Closing, new UI
