### ISSUE TITLE
[suggestion][preview] serve time gap ball animation after a point

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#425]
preview displays a ball animation to delay the next serve after completing a point. found myself making the ball toss motion out of habit right after a point (other player was ready to receive). might've looked like i was feinting, which might irritate some players. may be the ball animation can be shown to the receiving player as well (in case not being done already. haven't seen any such animations yet while receiving serves).

**Comment by dukeoflegs** [comment]
Closing, no longer an issue
