### ISSUE TITLE
[issue][preview] initial table position

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#426]
when i launch preview (on quest1), for some reason, the table always seems to appear more than a little towards my left initially. then when i long press x, it goes to my right. when i long press x again, it finally centers properly. this issue doesn't occur for me on the main version (where i usually only need to adjust the table height a little bit).

**Comment by dukeoflegs** [comment]
Closing, no longer an issue
