### ISSUE TITLE
An option to use [draggable positioning, always active] only with the non-racket controller

### ISSUE THREAD

**Issue by ghost** [ForFunLabs/ElevenPublicBugsAndAsks#427]
When "Draggable positioning, always active" is enabled, it's often triggered by fast racket movements, due to inertia (so even if the player doesn't accidentally press the button, it still activates sometimes due to mere inertia, because it's very light and doesn't require almost any pressure to move).

One of the possible solutions would be an option to use only the non-racket controller for draggable positioning

**Comment by carrotstien** [comment]
Hi,

What about the option of disabling racket hand input all together? That is
in the controller settings. Does that work for you?

-Roman

**Comment by ghost** [comment]
Thank you, that fixed this problem
