### ISSUE TITLE
Quickmatch Waiting Times

### ISSUE THREAD

**Issue by Andrew-McCauley** [ForFunLabs/ElevenPublicBugsAndAsks#428]
Posted this on facebook but thought I'd formalise it here.

A few people seem to think they are waiting much longer for QM than with the old system. I think there's a few things wrong with that. I think the most I've had to wait is maybe 2 minutes. I've waited FAR longer to get a game with an opponent within the bounds I've made for QM. So why do people think they're waiting longer?

I think waiting for something where you can "do something about it" (keep adding more challenges, see the list change etc.) gives the false impression of waiting less time, where with QM you just purely wait that time.

Player solution: just find something interesting to do in the meantime - ball machine training, lay against AI, whatever!

Possible dev solution: give more info on QM progression - maybe show where some games are getting close to completion in some way, which players are in the pool maybe, ELO ranges? Even "irrelevant info" that you can see maybe on the TV might ease people's feelings of waiting too long.

https://www.researchgate.net/publication/200085847_The_Psychology_of_waiting_lines might be worth a read, it's not super long and goes into some of the things I've mentioned and plenty of other things that might be able to be implemented.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue
