### ISSUE TITLE
More minigames would be easy (3 ideas)

### ISSUE THREAD

**Issue by tfforums** [ForFunLabs/ElevenPublicBugsAndAsks#429]
Idea #1: Ball launcher

A simple "return the balls" from a ball launcher mini game seems like it would be trivial to do but REALLY fun. 

Simply a ball launcher (like quadrants mini game)... launches balls ... all you have to do is get them back. 

There would have to be "rounds" of 5 or so balls one after another, so players could rest... this also serves as a "best" or score

Difficulty starts low, but the balls become faster  (both speed and / or time between launches) and better "serves" by the launcher (table placement) as the game goes on... 

try to get to round 20 etc

Idea #2:  All Serves AI 

Game of all serves. / what we call ping pong where i'm from... i.e. Serve as normal but the AI and user have to then bounce the ball on their side of the table (like a serve) on the returns  from there out. 

Idea #3:  Shot Trainer
AI serves, but on the net it says what type of shot you have to hit back:
-  top spin
-  back spin
- smash
- lob over the net (like a quadrant close to the net)
-  etc

**Comment by dukeoflegs** [comment]
Closing, ball machine
