### ISSUE TITLE
Cat mask is too bright and blends in with the ball in arena

### ISSUE THREAD

**Issue by ghost** [ForFunLabs/ElevenPublicBugsAndAsks#430]
In arena environment the ball blends in with the cat mask whenever the ball is going past it (or when using peripheral vision), making it difficult to return certain shots.

I've also noticed it's worse when you challenge someone, the cat mask is more illuminated then. When you are challenged, it's not as bright (but still bad). I think there is some lighting issue. 

Same / similar issues that have been mentioned in discord: 

https://discord.com/channels/340715434099605515/341248338445860866/917816533600862258
(about using cat mask to hide balls during serves; at the end of the message)

https://discord.com/channels/340715434099605515/581688710093996032/682357237435727884
(white, overblown cat mask)

https://discord.com/channels/340715434099605515/581688710093996032/843376057192808478
(about people mentioning lighting issue with cat mask in arena)

https://discord.com/channels/340715434099605515/340715434099605515/913653629007831050
(cat mask lit too brightly in chalet)

https://discord.com/channels/340715434099605515/581688710093996032/903144167813820426
(cat mask obscuring the ball in arena)

https://discord.com/channels/340715434099605515/340715434099605515/900362575156486164
(about a player using cat mask to hide the ball during serve)

https://discord.com/channels/340715434099605515/340717279299895297/871372743776546856
("the ball gets lost for half a second if it gets eye level between you and the cat face")

https://discord.com/channels/340715434099605515/340717279299895297/812079579811807252
("The orange one [ball] I would lose behind people who choose the cat face.")

https://discord.com/channels/340715434099605515/340715434099605515/808755472089743431
("cat avatar loads into the arena very strongly lit and looks blown out")

https://discord.com/channels/340715434099605515/340875662904524801/804386502133809162
(In a different context, but: "I guess the cat head is huge enough to hide a lot of movement")

Maybe a solution could be to add an option in debug settings to override any opponent's avatar with a gray headset avatar? This is probably simpler than editing the existing masks or UI.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue
