### ISSUE TITLE
Old Ball Sound enabled has a slightly higher start delay (around 20-25ms)

### ISSUE THREAD

**Issue by ghost** [ForFunLabs/ElevenPublicBugsAndAsks#431]
I've recorded a video of dropping a ball on the paddle with both "Old Ball Sound" enabled and disabled. Then I checked in a video editor how many frames pass between the lowest point of the ball before hitting the paddle and the beginning of the sound. It seems that when "Old Ball Sound" is enabled it usually takes one frame longer for the sound to play. The video is around 40fps according to mediainfo, so it seems that the default ("Old Ball Sound" enabled) has a 20-25ms delay. 

This should probably be confirmed with more testing, to make sure it's not just a wrong measurement. 

Decreasing sound latency would result in players reacting faster to the opponent hitting the ball (we react faster to auditory stimuli than to visual stimuli, and even faster to tactile stimuli)

**Comment by dukeoflegs** [comment]
Closing, new audio
