### ISSUE TITLE
Ball Machine Shuffle Distribution

### ISSUE THREAD

**Issue by jessejeter** [ForFunLabs/ElevenPublicBugsAndAsks#432]
The ball machine is awesome and highly customizable in its current state. But it's lacking a bit in one aspect of its randomization functionality. I've identified a shuffle button to randomize the shots I've defined. The only problem is it's a uniform randomization distribution. I'd love to be able to set the percentages associated with each preset shot I've defined.

For instance, I like to practice against a random topspin and a random backspin shot. But if I want to practice both at the same time, I have to accept that it's a 50% chance of topspin and 50% chance of backspin. Ideally, an 80-20 split would be preferable.

**Comment by carrotstien** [comment]
This is planned in the next ball machine update...along with a lot of other
things. For example..maybe you want a serve..followed with a certain set of
shots...ending with some defensive group of shot..and finally maybe a lob
for you to put away .....then repeat :)

**Comment by jessejeter** [comment]
That sounds awesome. Looking forward to the update!
