### ISSUE TITLE
[Feature request] An option to move notification square beyond / outside the net

### ISSUE THREAD

**Issue by ghost** [ForFunLabs/ElevenPublicBugsAndAsks#436]
The square with the notification icon makes it more difficult to aim for edge / corner shots:
![image](https://user-images.githubusercontent.com/35060206/152701829-a16bcea6-78aa-45e0-844d-d60dd1d1ff8f.png)

It would be nice to have an option to move it somewhere else, or hide it (leaving only the sound).

**Comment by dukeoflegs** [comment]
Closing, can be removed
