### ISSUE TITLE
[Quest][bug][0.04]  music settings cant be saved

### ISSUE THREAD

**Issue by Talwar85** [ForFunLabs/ElevenPublicBugsAndAsks#44]
I have to reset music settings every restart.

**Comment by ejblache** [comment]
It doesn't seem like any settings are saved - so please address more than just the music

**Comment by carrotstien** [comment]
should be fixed as of 0.5.2

**Comment by carrotstien** [comment]
@CallMeYohan  reopened..will close once i fully verify in quest , thanks

**Comment by carrotstien** [comment]
is it fixed as of 0.8.0?

**Comment by carrotstien** [comment]
should be fixed as of 0.9.3
