### ISSUE TITLE
[possible issue] ball lost during mp, possibly due to headset battery running very low

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#440]

**Comment by ab050505** [comment]
while playing AlErr070508 (https://www.elevenvr.net/eleven/1255810) in an unranked match (using my quest id), the ball somehow got lost (don't remember the exact sequence of events). tried for about a minute but the ball just did not appear while trying to toss (the other player too could see that the ball was not available). submitted logs under mp/performance a couple of times. but then my headset battery ran out (it is possible the issue itself was caused by the headset battery being very low).

**Comment by dukeoflegs** [comment]
Closing, no longer an issue
