### ISSUE TITLE
Match result is not correctly recorded for unranked games played in multi-player room

### ISSUE THREAD

**Issue by jliminh** [ForFunLabs/ElevenPublicBugsAndAsks#442]
Recent days my friends and I played in room number "666666" every night . 2 players play an unranked match , the others watch them play around the table. There is also a camera setup in the room ，which runs a ETT oculus PC client.
The problem is that result is not correctly recorded for any match in the room.
Please help fix it. Great thanks! 
![image](https://user-images.githubusercontent.com/105851157/200450637-18ca98e2-cd28-4eec-b022-c950909a9b93.png)

**Comment by dukeoflegs** [comment]
Closing, no longer an issue
