### ISSUE TITLE
Show last Opponent as a 3rd tab in the "Friends" / "Lobby" Display on the Right when not in a game to aid in Friending and Blocking.

### ISSUE THREAD

**Issue by SurfCatten** [ForFunLabs/ElevenPublicBugsAndAsks#443]
Right now, to see Match History in order to quickly Friend or Block someone that you have played, after the game has ended, you have to go to: "menu->multiplayer->profile->match history" and then click on the Person you just played.  As I tend to Friend or Block many new people I play, this is many extra steps.

It would be very helpful if the most recent person / people played showed up as a 3rd tab in the "Friends" / "Lobby" Display on the Right when not in a game.  (During a game, of course, this IS where the person you are playing shows up).  It doesn't need to be the complete match history - just the last person played.

**Comment by dukeoflegs** [comment]
Closing, new UI
