### ISSUE TITLE
Show the Number when Adjusting Table Height Slider

### ISSUE THREAD

**Issue by SurfCatten** [ForFunLabs/ElevenPublicBugsAndAsks#445]
The Occulus Quest will often change the Guardian Floor Level before and sometimes during a game (Usuallly due to losing tracking when different lighting conditions exist).  This means I and others often have to adjust the Table Height after starting ETT and sometimes between games.

ETT does a great job of allowing the independent movement of the table to help with this (I use your recommended method of putting one controller on the floor under the edge of the table and setting the height with the other contrroller for this)

One thing that would help even more is if a number could be displayed after clicking the set button and also when moving the slider.  It can be a number which reflects the table height, or the player height - not sure how it works now - but then I could remember that number and make sure it is the same each time, rather than clicking the "set" button several times and seeing the table jump up and down and then guestimating that it is in the right position (I don't have a good landmark on my body for the table height).  Also then I could be certain if it is ETT resetting the Table Height when I start up or a change due to a change in the Quest tracking.

**Comment by carrotstien** [comment]
hi. Unfortunately, there is no reference point. Whatever number you set would only be relative to the guardian floor. 

The closest thing you can do is set the table height as perfectly as you can...and then stand up straight and save the table height relative to your head

**Comment by dukeoflegs** [comment]
Closing, per comment
