### ISSUE TITLE
Bug fix? Request - In the Unrated Lobby, after sorting by Rating, new players who come online are not sorted in the correct order.

### ISSUE THREAD

**Issue by SurfCatten** [ForFunLabs/ElevenPublicBugsAndAsks#446]
In the Unrated Lobby, when sorting by Rating (clicking the column header once or twice), new payers who come online after the list is sorted do not show up in the selected sort order, requiring resorting the list to be resorted by clicking on the column header again.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue
