### ISSUE TITLE
Dis-allow or lose point if walk into Table.

### ISSUE THREAD

**Issue by SurfCatten** [ForFunLabs/ElevenPublicBugsAndAsks#447]
Many times opponenets (and sometimes myself) unknowingly walk a little into the end of the table when returning a hard to hit ball.  I understand that people with longer arms can bend over and reach over the table but is there a way to track where someone is standing to determine if they have walked into the table and prevent it?

**Comment by carrotstien** [comment]
Not really. We can make guesses, but we want to be very sure about our
accuracy before we make a determination.

**Comment by dukeoflegs** [comment]
Closing
