### ISSUE TITLE
[Feature request] AR/Passthrough mode 

### ISSUE THREAD

**Issue by jackchua65** [ForFunLabs/ElevenPublicBugsAndAsks#449]
Can we have a augmented reality mode? I mean the background just make it passthrough. It is useful as you can see your room without hitting some object if your space is small.

**Comment by carrotstien** [comment]
hi (responded in discord as well):

hi @jackchua65 that is planned, but it is behind a technical wall right now
we can't just cross

**Comment by dukeoflegs** [comment]
Closing, no longer an issue
