### ISSUE TITLE
ping based filters

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#452]
in the pre-nui versions, i used to regularly play with people who had one ping bar or even no bars at all. there seemed to very little to no difference compared to playing with people with more bars. so the ping/connection quality calculation does not seem to reflect the actual quality of the connection (i happen to have excellent internet connectivity and live in an area that has cloud data centers (amazon, microsoft etc)). in the nui version, there seem to be far fewer players in the unranked lobby (after nui went live recently). *if* this is due to the new ping based filters, then please reconsider these, at least for unranked play (or make the connection quality calculation process more accurate).

**Comment by ab050505** [comment]
not sure what happened but i am now able to see players with various pings (red, orange, green etc) like before in the unranked lobby in nui. i had switched to the non-nui version for a day and then switched back to nui today. may be that fixed it somehow. it is also possible that i did not notice the "done" button at the (far) bottom right of the filters pane the last time. i may have been just selecting a filter option and simply hitting the back button at the top left (which is how other settings like audio, graphics etc work). in case the "done" button is really needed at the bottom right, then there should probably be some confirmation dialog when a player changes the filter setting and tries to go back without clicking the "done" button.

but in general, with regard to filters, i totally agree with the following (which i just came across):
![image](https://user-images.githubusercontent.com/28642046/232320836-357ee7e7-3b1d-4630-b4ff-629aa1b54d01.png)

**Comment by dukeoflegs** [comment]
Closing, filters available
