### ISSUE TITLE
Serving with one hand fails at 50% of the time

### ISSUE THREAD

**Issue by AndriiSamsonov** [ForFunLabs/ElevenPublicBugsAndAsks#453]
First of all, I want to say that this is the best computer game I have ever seen. I am very grateful to the developers for the opportunity to fully play sports at my age after fifty years.

A few weeks ago one of my touch controllers broke. I tried to solve the issue with Meta support but they didn't help me so I ordered a new one. Doesn't matter. The important thing is that I stayed with one controller for several weeks. I selected the option to serve with one hand (advanced settings -> controllers -> more -> toss from paddle hand). However, it turned out that it is very difficult to serve with one hand. When I toss the ball up, very often a micro-bounce of the ball on the paddle occurs and it detects a hit while the ball is rising. So about half of my serves fail already at the ball tossing stage. When I'm in the Serve Practice mode, it says "service hit was while ball was rising".

Could you fix this? For example, don't fix the hit of the ball on the paddle while serving until the ball moves away from the paddle at some distance (e.g. 5 or 10 mm).

**Comment by AndriiSamsonov** [comment]
On the Discord forum I was advised to adjust the ball toss position to not be within the paddle. This workaround really works. So setting such ball position by default can be a solution of the issue.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue
