### ISSUE TITLE
[quest3][preview 0.313.0] miscellaneous

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#455]
1. when we are in chalet, arena etc., environment automatically switches to studio when we opt to play an sp match with ai.
2. the serve indicator arrow that is displayed at the net is not getting updated properly. seems to get stuck to one side of the net, regardless of whose turn it is to serve.

**Comment by carrotstien** [comment]
re 1. the environment is separately selected for single player match. It is
a bit weird - we will likely change it.
2. will check

**Comment by ab050505** [comment]
(re 1: actually, looks like the environment change to studio on sp match happens while playing after the initial installation. the behavior seems to change when we play eleven again later on. in the most recent session, when i switched from arena to chalet and then opted to play an sp match, the environment changed back to arena for the sp match. definitely a bit weird.
re 2: btw, the serve indicator arrow does not appear at all initially when we start playing an sp match. it appears when we open and close the menu (and then gets stuck to one side of the net))

**Comment by ab050505** [comment]
0.313.2:
other player's match history seems to be appearing under mine. i had just finished playing "stigan" and went into my match "history" to try to add them as a friend. noticed that the first two matches in the history list are not matches played by me. they seem to be related to matches played/being played by "stigan" with somebody else (screenshots below)

![image](https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/assets/28642046/bd421cb5-b5ff-47b7-adb5-e4539e7c0817)

![image](https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/assets/28642046/08dec7fe-bda8-46c7-8dbf-262bd2e9acc4)

**Comment by ab050505** [comment]
(realized during the latest session that, when i check history after playing a match with somebody, all of the matches shown in the list are actually those of that player. these include the matches that that player has played with me as well (my quest id is kr1010). however, if i check history right after launching eleven, the list shown is correct ie., the list of matches that i had played earlier.)

**Comment by ab050505** [comment]
(checked history in the game after a couple of mp matches today and it seemed to be working fine today ie., my own match history was being shown)

**Comment by ab050505** [comment]
(spelling mistake ("alternatate"))

![image](https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/assets/28642046/f111bbba-6fed-4be3-8e16-e81724e90866)

**Comment by ab050505** [comment]
(a couple of days ago, during an mp match, the other player suddenly froze, apparently due to some network connectivity issue on their side. i tried to exit the room etc. but nothing seemed to work and the game ui in general became very "laggy". things started working properly again after a popup saying something like "you won" appeared (i had submitted logs through the game that day (kr1010) but could not submit a detailed description until now). others had also earlier mentioned this type of behavior (probably due to the use of blocking socket calls, from my limited knowledge). if possible, may be a message like "trying to restore lost connection. please wait." can be displayed somewhere as soon as eleven detects any such network issues, to avoid unsettling players.)

**Comment by ab050505** [comment]
(during another episode of "opponent frozen and game ui lagging due to some connectivity issue" today, noticed that it says "connecting" near the top of the left side panel when we bring up the menu. so, to improve user experience a little bit, it might also be possible to display something like "reconnecting, please wait..." somewhere near the net right after connectivity gets broken. btw, the "you won" type pop up did not appear today even after waiting for 2-3 minutes but i managed to exit the room via the "exit room" button after a few attempts.)

![image](https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/assets/28642046/082233dd-1e2f-48eb-9945-4a1661ba10cb)

**Comment by ab050505** [comment]
(0.313.13) played a couple of mp matches on this version and history seems to be displaying properly (one minor issue: the times shown against the matches in the history list should ideally be the player's local times. currently they are in utc.)

![image](https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/assets/28642046/2e5e1e14-aada-4174-9933-1040f840efe9)

**Comment by ab050505** [comment]
while playing "potetomato" a few minutes back, at one point during the match, between... points (or may be sets), the ball seemed to get lost. submitted a bug report immediately. but a few seconds later, "potetomato" seemed to be able to summon the ball and we continued the match. may be the ball did not really get lost and i just got that impression due to getting disoriented by the fact that the table suddenly did not show any of the usual indications of the current state of the match (whose turn it was to serve, the current points score (0-0) etc.).

**Comment by ab050505** [comment]
pretty sure the ball got lost while i was playing with "bah-smash" a few hours ago. immediately submitted logs (mp->performance). we had played two points at the start of a new match. i lost both the points but the score seemed to remain stuck at 0-0 until the ball got lost. then, while i was submitting logs/bug report, "bah-smash" seemed to reset the ball (going by the fact that a "ball reset event" message appeared) and the score updated to 0-2. i resubmitted the logs (mp->performance. description: "p2"). "bah-smash" left the room soon after.

**Comment by ab050505** [comment]
while playing "turtlehead" just now, the table again became blank after playing a couple of points. the usual indicators on the table (whose turn it is to serve, the players' names, the current set score, etc.) disappeared. submitted a bug report in game (mp->performance). 
by the time i could complete submitting the bug report (may be about 5 seconds), "turtlehead" lost patience and left the room. now, on elevenvr.net and on clubhouse, the score for this match is being shown as 0-0 (even though i am sure that we played at least one full point (which i had won)).

**Comment by ab050505** [comment]
[preview 0.314.10](i am on the preview channel and can see 0.314.12 in live but only 0.314.10 in preview)
started playing "paulluap" a few minutes ago. after the very first point, the table markings disappeared and the ball got lost. submitted a bug report immediately (mp->performance). as far as i can recall, this is what happened (i generally play in an absent minded way): after starting the match with paulluap, i served first. after a bit of back and forth, paulluap tried to backhand smash my return and missed hitting the ball. i started my serve again and noticed that the table markings had disappeared and i was not able to summon the ball. paulluap indicated that they too were not able to summon the ball.

**Comment by ab050505** [comment]
after the above episode, i had exited eleven for a while. when i re-entered eleven about 10 minutes later, somebody else's avatar was being shown in my profile:

![image](https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/assets/28642046/39e887c9-6710-462f-a485-9aa2ca097ce2)

reminded me of somebody i played recently. thought it might be paulluap. so looked up the player on clubhouse and saw my current avatar image being shown against that player in the search results: 
![image](https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/assets/28642046/9744d523-684c-4d3b-87d6-47deca70214e)

but when i clicked on the search result, the avatar shown in the profile page is different again.

when i relaunched eleven again a few minutes ago, the avatar image is again back to normal.

(may be this is all meta related)

**Comment by ab050505** [comment]
ball got lost in two matches back to back today. the first match was with "mufan". i noticed after playing the first point that the table markings were missing. i stopped to send logs and then realized that i was not able to summon the ball either. after a couple of minutes, "mufan" left the room and there was a message at the net saying that i had won "na-na". before "mufan" left the room, the tv was showing a message that the toss was too low. then, when i checked the tv again after they left the room, it was showing something like "did not hit the ball after it landed on the table". i then started a match with "cy-borg". again, the table markings disappeared and ball went missing after the first point. sent logs. then saw several "ball reset event" messages at the net over the next few minutes. may be "cy-borg" was sending the logs repeatedly or doing something else. after about 4-5 minutes, "cy-borg" finally managed to summon the ball and we continued playing, without any further issues. (checked elevenvr.net now and the first score between "cy-borg" and me today is being shown as 0-0)

**Comment by ab050505** [comment]
ball got lost while playing "Polyphia n u" last thursday (match #47908012). i was recording the entire session that day to see if i can record a ball loss episode. playing while recording seems to work well in quest 3 but unfortunately, the video recording does not seem to get synced to the gallery in the mobile meta quest app for quick sharing (it appears in the gallery but we cannot open it). finally found time today to connect quest 3 to pc and to extract the relevant clip:
https://clipchamp.com/watch/dKyQPoTzGdM

**Comment by dukeoflegs** [comment]
Closing, various issues
