### ISSUE TITLE
UI - Speed and Rotation on the TV screen are squares.

### ISSUE THREAD

**Issue by dukeoflegs** [ForFunLabs/ElevenPublicBugsAndAsks#459]
![image](https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/assets/110847173/8b4478cf-c580-4447-b7fb-1c46e0ad8542)

Unable to reproduce.  Steps will be added when reproduced.

**Comment by dukeoflegs** [comment]
Steps:
1. Load game - do not hit ball once loaded.
2. Change language to any other language.
3. Hit ball and observe text on TV.

Note: If you hit the ball before changing language this issue will not occur.

**Comment by dukeoflegs** [comment]
Another Repro:
1. Select a mini-game other than Free Play.
2. Play the mini-game and exit.
3. Select the Free Play mini-game.
4. Hit the ball and observe the TV.

**Comment by carrotstien** [comment]
fixed a couple of versions ago
