### ISSUE TITLE
Bugs and more for quest 0.0.4

### ISSUE THREAD

**Issue by DoggyP0O** [ForFunLabs/ElevenPublicBugsAndAsks#46]
bugs:
- Multiplayer often gets disabled randomly. Seems like it gets disconnected from my wifi entirely. Need to restart to fix
- Guardian gets re-enabled randomly. Need to turn off and on the guardian to fix.

- multiplayer seems to lag. It's almost like in live except the delay is when I hit it and not when my opponent hits it. Or maybe it's just regular lag
- that voip issue still there

- Wish you could just save table position so I don't have to reset it every time I take it off.
- paddle position also doesn't save.

- tossing the ball is a lot slower. 

- ball very often clips through my paddle and uses the backside of my paddle to register the hit. It does happen for slower hits as well as the faster hits.

others:
- that new table bounce allows for some DIRTY serves, that are completely allowed irl and not at all considered rude in most circumstances, that I will exclusively using. Nobody should have the excuse of space now that we have a quest too! And if anybody uses it on me, I can just smash it, because that got more doable as well. Every point in my games will be 1-2 hits.

**Comment by carrotstien** [comment]
closing this as many issues are solved. For anything left, please open a new ticket, one per issue. 

thx.
