### ISSUE TITLE
Can‘t buy the program in meta store after expiring 15 min. testphase…

### ISSUE THREAD

**Issue by thomasedgarb** [ForFunLabs/ElevenPublicBugsAndAsks#463]
It says „test phase expires“ and give the options to end game or buy in store… but in store there is not button to pay for the program… Maybe it could be paid inner testphase only… if testphase expires there are no option to pay afterwards… i‘m quite confused…
Best regards
Thomas Bader

**Comment by carrotstien** [comment]
can you share your oculus email so that i can contact oculus about it to have them look into this.

**Comment by carrotstien** [comment]
you can email your oculus email to support@forfunlabs.com (so you don't post it here since here is public)

**Comment by thomasedgarb** [comment]
thank you for your response… i‘m a bit confused in that … i‘m not a native english speaker … we can switch to german?

**Comment by thomasedgarb** [comment]
Hello RomanThe mail is use for my Meta Account is the same as we‘re use it for this request…So you can take „ ***@***.*** „Mit freundlichem GrußThomasAm 03.05.2024 um 19:12 schrieb Roman Rekhler ***@***.***>:﻿
you can email your oculus email to ***@***.*** (so you don't post it here since here is public)

**Comment by carrotstien** [comment]
Können Sie Ihre Oculus-E-Mail-Adresse teilen, damit ich Oculus kontaktieren kann, um dies prüfen zu lassen? Sie können Ihre Oculus-E-Mail an support@forfunlabs.com senden (damit Sie sie hier nicht öffentlich posten).

**Comment by carrotstien** [comment]
Ich sehe die E-Mail, die mit Ihrem GitHub-Konto verknüpft ist, nicht.

**Comment by thomasedgarb** [comment]
Tut mir leid, dass ich scheinbar schwerer verstehe als der Durchschnitt :-)Ich hatte gedacht du meintest die Mailadresse zu meinem Meta account… anyway… Die Mailadresse zum GitHub account ist aber die gleiche : „ ***@***.*** „Mit freundlichem GrußThomasAm 03.05.2024 um 20:38 schrieb Roman Rekhler ***@***.***>:﻿
Ich sehe die E-Mail, die mit Ihrem GitHub-Konto verknüpft ist, nicht.

**Comment by carrotstien** [comment]
Ja, ich suche nach der E-Mail-Adresse, die mit Ihrem Oculus-Konto verknüpft ist. E-Mails werden in GitHub automatisch zensiert, daher bitte ich Sie, die Informationen an die E-Mail-Adresse weiterzuleiten, die sich zusammensetzt aus:

"support", dem @-Symbol, dann forfunlabs.com.

**Comment by carrotstien** [comment]
if anyone is reading this, the solution is the buy it on oculus pcvr and that will grant it to you on mobile
