### ISSUE TITLE
Arena Lighting is too dark in the new version

### ISSUE THREAD

**Issue by carrotstien** [ForFunLabs/ElevenPublicBugsAndAsks#464]
![image](https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/assets/234703/3c274a25-a754-49a2-95d6-84a42697b3c4)
https://discord.com/channels/340715434099605515/340717174907863051/1238127211605786705

**Comment by dukeoflegs** [comment]
Closing, new lighting
