### ISSUE TITLE
Game doesnt end when 2 points clear after 10-10

### ISSUE THREAD

**Issue by ironymanvr** [ForFunLabs/ElevenPublicBugsAndAsks#47]
Had some scoring issues with ai where it didnt see the game as over at 12-10 and eventually conceded it at 15:12. Plus I'm pretty sure i should have lost the last point as my memory is that i hit it into the net but it seemed to count it against ai so i am wondering if the game was reversing the scoring in some way hence the failure to recognise the win previously?

![image](https://user-images.githubusercontent.com/51400184/59109856-beddf500-8935-11e9-8e21-a85e6d40aa5d.png)

**Comment by carrotstien** [comment]
should be fixed as of 0.5.2
