### ISSUE TITLE
AI overshoots after game being open for too long

### ISSUE THREAD

**Issue by kat9274** [ForFunLabs/ElevenPublicBugsAndAsks#48]
[Quest][Bug]

The steps to recreate this bug are:

1.Open eleven table tennis

2.Hit the ball a few times

3.Take off your headset

4.Tap the power button while outside of gardian (not sure if needed)

5.Wait 1+ hr

6.Hit with the ai and the bug should be noticable

**Comment by carrotstien** [comment]
Frankie69 has confirmed as well

**Comment by carrotstien** [comment]
fixed v 0.36
