### ISSUE TITLE
Game stopping during power forehand shot 

### ISSUE THREAD

**Issue by SOUPDOGG** [ForFunLabs/ElevenPublicBugsAndAsks#51]
Hi was in middle of single player game, my backhand is getting much more powerful now, so I thought let’s see how my forehand power is, took a ball about mid height with a forehand power drive as the paddle connected with the ball, I got strong hepatic feedback as you would but it lasted at least a second and Eleven vr beta just stopped and I was in quest home room with no game running

**Comment by ironymanvr** [comment]
Exact same happened to me fyi.

**Comment by SOUPDOGG** [comment]
Have not had this happen in a while now ( at least a week ) not sure if oculus has sorted something or carrot 👍

**Comment by carrotstien** [comment]
has this happened to anyone outside of hitting against AI? has it only happened in single player mode, or in home view as well?

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
