### ISSUE TITLE
AI doesn't move when hit off table

### ISSUE THREAD

**Issue by slydog43** [ForFunLabs/ElevenPublicBugsAndAsks#53]
I think it would be more realistic if the AI moves after every shot I make even if its going off the table.  Right now the AI doesn't move when "it" knows its going off the table.  Hope this makes sense.

**Comment by BryceKKelly** [comment]
To add to this - if the ball is going off table, the AI will freeze, and frequently this results in the ball hitting their paddle and they lose a point. At first I thought it was intentional AI mistakes but even the world class setting does it.

**Comment by dukeoflegs** [comment]
Closing, no longer an issue.
