### ISSUE TITLE
AI stops when it is it's turn to serve

### ISSUE THREAD

**Issue by ironymanvr** [ForFunLabs/ElevenPublicBugsAndAsks#54]
Happened a few times in succession even with game restart in between. Basically started SP match, served twice and then when it was AI's turn to serve it just did nothing.

**Comment by Llamalland** [comment]
For me, AI stopped after the 3rd point, it served once then never again. This happens every time.

**Comment by ironymanvr** [comment]
yes - that sounds about right although IIRC it was on the AI's first serve so on the third point rather than after but I could have recalled incorrectly. FWIW - that did stop happening for me but not sure why as after various shutdowns etc. it started working.

**Comment by carrotstien** [comment]
can you guys let me know if it still happens as of 0.5.2 ?
@ironymanvr  @Llamalland

**Comment by Llamalland** [comment]
@carrotstien Seems to have fixed itself at least for me with the update :)

**Comment by engineeringpatrick** [comment]
@carrotstien Happened to be just today with Oculus Rift S & SteamVR, AI in hard mode stopped when it was his turn to serve

**Comment by carrotstien** [comment]
is this still happening after today's push 0.9.3?

**Comment by carrotstien** [comment]
fixed v 0.36.0
