### ISSUE TITLE
Not sure this is the right place, profiles wanted to save paddle hand position

### ISSUE THREAD

**Issue by slydog43** [ForFunLabs/ElevenPublicBugsAndAsks#58]
I love showing off ETT to people, but want to save my current paddle position so new users can fine tune their paddles and I can go back to my settings easily.  I hope this is not in a completely wrong spot.

**Comment by carrotstien** [comment]
You can currently make presets up to 5 or 6 i think. Are you talking about
something else?

**Comment by carrotstien** [comment]
closing as i think this is resolved
