### ISSUE TITLE
[Quest][Suggestion]

### ISSUE THREAD

**Issue by Expicot** [ForFunLabs/ElevenPublicBugsAndAsks#61]
When launching the ball with the free hand, that one is moving quite 'slowly' compare to what a IRL player would 'expect'. IRL, a small move of the fingers or the wrist is enough to launch a ball quite high, but in VR the whole hand have to move to give enough speed to the ball. I would suggest to 'cheat' the speed communicated to the ball ( a multiplier like x1.5 ?) when launching it. I have the same issue with RF and it is quite annoying because the ball is partially hidden by the controller and hard to target.

**Comment by carrotstien** [comment]
since then tracking methods have updated, should be good now
