### ISSUE TITLE
legacy studio look as an option

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#68]
please consider providing the legacy version studio look as an option. the current studio look is cool as well but already feeling a bit nostalgic for the old look. also it might help old-timers identify game play related changes for the worse w.r.t legacy version more easily.

**Comment by ab050505** [comment]
i am now able to access the original/legacy version through my steam copy of eleven (which i had bought along with the oculus version last year (as a small token of my appreciation) and then forgotten all about). so i personally seem to be all set in this regard (just need to figure out a way to prevent steam from auto-updating the game, so that i don't end up with the new version on steam as well later on (after the revamped version is released on steam as well)).

**Comment by carrotstien** [comment]
it's a bit hard because a big part of the changes to the studio are to make it a lot more efficient so it can run on quest fine. It'd be hard to have environments different between platforms - we'd prefer to have good looking envs for all, but the same.
