### ISSUE TITLE
Something doesn’t seem right 

### ISSUE THREAD

**Issue by SOUPDOGG** [ForFunLabs/ElevenPublicBugsAndAsks#69]
Right was playing someone yesterday MP hitting with each other do not know what settings he had but it seemed ridiculous he would hit the ball pretty much flat bat soft/medium strength serve (middle to middle) maybe a small amount of topspin and it was like he had put the most amount of topspin I’d ever received from such a hit the ball was dropping so quick, it wasn’t shooting at me off the table as a hit with that much spin should do just dropping like it, I’ve been testing today and have the feeling like there’s 2x gravity everything I’m hitting is coming dropping so fast. I’m flat batting hits/serves to 1’ from my end from a 1’ height off table fast speed that should then hit the wardrobe 3/4 the way up (above clothing) and the ball is dropping to between before wardrobe and 3’ up wardrobe, I’ve been wondering for a few days how some of my shots/strokes have been landing on the table when they should be going way past. There definitely seems to be something wrong with the atmosphere. 
After playing legacy for 4-5hrs last night that seemed much closer to real life regarding atmosphere/gravity and speed speed. It’s like the only thing that needed changing from legacy to this beta version is the actual stroke/collision off bat physics.
Pretty much just put the Ai’s/bats  new stroke physics into legacy version or put the atmosphere/gravity into this new version <@249332717848756224>

**Comment by carrotstien** [comment]
i think this can be closed now. If you have future similar issues, please open a new ticket, and try to keep the scope small.... better to open multiple tickets than one big one
