### ISSUE TITLE
AI Backhand Error

### ISSUE THREAD

**Issue by cjrust** [ForFunLabs/ElevenPublicBugsAndAsks#7]
I see that the AI is able to hit forehands from anywhere on the table, but in the semi-pro and legendary modes, the AI will try and fail to hit a backhand. This only happens if I lob the ball up to eye-level height, and only on these two levels of difficulty. When replicating it, I'd say it happens 8/10 times when I hit that lob shot. The AI just turns its paddle to the backhand side (black side of paddle) and doesn't attempt to swing at the ball, losing the point.

**Comment by carrotstien** [comment]
haha, it's def not trying to hit a back hand..but that is a bug in the current AI ^_^ 
thanks for posting, will update this when AI can hit backhands

**Comment by carrotstien** [comment]
should be fixed as of 0.5.2
