### ISSUE TITLE
(Big) Invisible opponents balls 

### ISSUE THREAD

**Issue by SOUPDOGG** [ForFunLabs/ElevenPublicBugsAndAsks#70]
both myself and opponents balls could not be seen by each other, when first transported into room for a split second did see him make one serve/ball go past me then he made strokes but I could not see ball, I could serve with my ball but he could not see it either. Left room returned to new request about 5 times and still the same happened

**Comment by carrotstien** [comment]
> Soup_DoggToday at 5:31 PM
Yep never seen anything like it before, 
The request came whilst I was in ball machine mode thou and I’ve never gone to a multiplayer game from that before

**Comment by GeneralFailure-ch** [comment]
I had twice some kind of same problem with invisible Balls. 
On my side the ball was visible for both of us. On opponents side, his ball and serve was invisible for me, but visible for the Opponent. So i served all the balls and Opponent returned it... strange happend only twice... and i was not able to reproduce it...
(I play Standard Rift)

**Comment by carrotstien** [comment]
hmm, let me know if it has happened since 0.9.3 (just pushed)

**Comment by carrotstien** [comment]
i believe this is no longer an issue, but reopen and let me know if it is
