### ISSUE TITLE
Aproximate ball from ballmachine

### ISSUE THREAD

**Issue by captnchr1s** [ForFunLabs/ElevenPublicBugsAndAsks#71]
Could you please aproximate the way of the ball by a line in the air, while manipulating the ball machine for horizontal/vertical and power? 

Thanks!

**Comment by carrotstien** [comment]
Yes, will add...meanwhile what you can do is just maximize the rate, and
that will shoot so many balls it might as well be a trace :)

**Comment by carrotstien** [comment]
in game now
