### ISSUE TITLE
[Suggestion] Selecting the number of sets to play with bot

### ISSUE THREAD

**Issue by engineeringpatrick** [ForFunLabs/ElevenPublicBugsAndAsks#74]
**1.**  
Being able to select the number of sets to play with a bot before starting (and also remembering the selected mode, as a preference). 
Example:
Quick game -> Best of one
Normal -> Best of three
Long game -> Best of five
Professional -> Best of seven

Or maybe even being able to select as many sets and points as you wish, even crazy stuff like best-of-nine sets and every set you reach 5 points or something like that.

**2.** 
Total match score displayed on the TV screen. Right now only the set points are displayed on the TV :(

**Comment by carrotstien** [comment]
now when you play the bot, or unranked you can play on and on and on - scoreboard and tv reflects


..though in writing this, i think the tv might show weird stuff after 3 games won :|
