### ISSUE TITLE
Oculus controller visible through paddle 

### ISSUE THREAD

**Issue by StownieDaze** [ForFunLabs/ElevenPublicBugsAndAsks#75]
when playing online i could see my opponents in game oculus controller through his paddle. so on the left hand i could see his oculus controller as normal, but on the right hand where there would normally just be a paddle and no visible controller, i could see his paddle AND his controller. as though his state was still stuck in the 'change paddle orientation' menu but he could freely play.

**Comment by carrotstien** [comment]
should be fixed as of 0.9.3
