### ISSUE TITLE
( bug ) (quest) Ball sticking on throw  

### ISSUE THREAD

**Issue by SOUPDOGG** [ForFunLabs/ElevenPublicBugsAndAsks#79]
Hi ball is not instantly letting go when realeasing trigger. 
Is a little better when positioning controller sideways like you would hold your hand when doing a real in life service throw up. 
It feels like it only happens for a few m/s but is noticeable.

**Comment by Bubak** [comment]
practice more ... my first thought was the same. not anymore.

**Comment by Rutzensior** [comment]
i agree with soupdogg, ball sticks to hand a bit then appears again on impact when the opponent serves.

**Comment by carrotstien** [comment]
@Rutzensior , this isn't related to MP, @SOUPDOGG  meant in your own view

**Comment by StownieDaze** [comment]
i've mentioned this several times. @Bubak thats a very 'get good noob' response to something that is an actual issue related to the game, not to the person playing it.

**Comment by carrotstien** [comment]
@SOUPDOGG  how does it feel as of 0.9.3?

**Comment by carrotstien** [comment]
fixed
