### ISSUE TITLE
Sometimes the serve is counted as a failure

### ISSUE THREAD

**Issue by weathondev** [ForFunLabs/ElevenPublicBugsAndAsks#8]
Imho the serve was totally fine but it was counted as a failure.
Sometimes my serve is counted as a faulty one, it seems to happen when i leave my left hand close to the ball i'm hitting.
https://streamable.com/t3dm9

**Comment by carrotstien** [comment]
Service Rules
The service must start with the ball in an open palm. This stops you from throwing it up with spin.
**The ball must be thrown vertically, at least 16 cm. ...**
**The ball must be above and behind the table throughout the serve. ...**
After throwing the ball, the server must get their free arm and hand out of the way.

(only the bold are enforced)
