### ISSUE TITLE
(Bug) (Quest+) no head and ball serve position 

### ISSUE THREAD

**Issue by SOUPDOGG** [ForFunLabs/ElevenPublicBugsAndAsks#80]
It’s also hard to play against someone without a head/body 
Played sormie and bigpaff and neither had a head or body also when they went to serve the ball was just stuck in mid air and then came at me from a different position ( if that makes any sense ) it’s like the real ball is invisible and it’s showing a fake one in a static position until the invisible one is hit by bat and then that one becomes the real ball.

**Comment by carrotstien** [comment]
i think fixed as of 0.8.0. head and voice should be good..not certain about ball

**Comment by carrotstien** [comment]
should be fixed as of 0.9.3
