### ISSUE TITLE
Paddles duplicating after opening the steamvr menu

### ISSUE THREAD

**Issue by 3VERYTHINGISTAKEN** [ForFunLabs/ElevenPublicBugsAndAsks#82]
So whenever you open the steamvr menu (vive bottom button) and then go back ingame, my paddles apparently duplicates from my opponents perspective, i couldnt see it, only he could.

**Comment by carrotstien** [comment]
can you check if this is happening to you still as of today's push 0.9.3

**Comment by carrotstien** [comment]
I think it is resolved, reopen if it's not
