### ISSUE TITLE
Ball stuck in hand after disconnecting from online match

### ISSUE THREAD

**Issue by StownieDaze** [ForFunLabs/ElevenPublicBugsAndAsks#83]
was playing with someone online and i believe we dc'd, not sure if it was him or me or both. but after he disappeared the ball was stuck in my hand and i couldnt release but i still remained in the online room (i now know that we're not instantly kicked out of the room now upon disconnecting after already speaking to Roman about this.) after leaving the online room and going back to single player i was able to freely throw the ball again as normal
https://streamable.com/lh88g (video of the incident)

**Comment by carrotstien** [comment]
fixed v 0.36.0
