### ISSUE TITLE
Ball toss button is sometimes locked to my left hand

### ISSUE THREAD

**Issue by 3VERYTHINGISTAKEN** [ForFunLabs/ElevenPublicBugsAndAsks#85]
So if i have the paddle on my left hand, i should be able to press the right hand trigger (vive) for the ball to appear in there, but what happens is that i have to press the left hand trigger and it will appear on my right hand, doesnt happen all the time and it can be fixed if i restart the game a couple of times, so its not that big but its there.

**Comment by carrotstien** [comment]
yea this is a bug, will be fixed in next patch

**Comment by carrotstien** [comment]
should be fixed as of 0.9.3

**Comment by carrotstien** [comment]
closing as i believe it is fixed
