### ISSUE TITLE
Problems with ball sound.

### ISSUE THREAD

**Issue by Zuorro** [ForFunLabs/ElevenPublicBugsAndAsks#87]
Hey! :)

I think that the sound of the ball sounds as if I was hitting it with a wooden paddle without rubbers. It's just not how it sounds in real life.
The other thing is that the volume range of this sound is too wide - I mean it is quiet, when it bounces on the opponents side (which might be okay in general :), but it's definitely too loud when I hit it at my side (especially close to my ears).
Decreasing the ball volume doesn't resolve the problem.
Simply - the ball sound should be different (less wooden?) and less louder on my side.
I also noticed that there is no sound when the opponent hit the ball.

**Comment by carrotstien** [comment]
1. yea we are working on the sound to make it better...it's actually suuuper hard to make it sound right, but i agree it sounds bad now
2. i think we mostly need to update the ball volume decay functionality. Probably something custom. 
3. I'm thinking of recording a couple of sounds with different paddles, and letting the user pick the sound they like the most. Some paddles sound more wooden.

**Comment by dukeoflegs** [comment]
Closing, updated sounds in game.
