### ISSUE TITLE
ball seemed to disappear

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#89]
(rift) while playing legendary, at one point, the ball seemed to become unavailable. i think i had just won a point (the ball had bounced high during the game or something (can't recall exactly what happened but it was not a normal rally)). i tried to serve again but the ball simply would not appear when i tried the usual ball toss move (several times). i was able to move the table around, so the left touch controller seemed to be alright (i had put in fresh batteries in both controllers just before the session). i waited for a bit to see if ai would serve (in case it was its turn) but it did not. finally i had to end the game. things worked fine again when i started a fresh game (with legendary). following image shows the contents of the tv screen during the time that the ball became unavailable:

![image](https://user-images.githubusercontent.com/28642046/61307324-c1bce700-a80b-11e9-95e3-d631ceec79ff.png)

**Comment by ab050505** [comment]
could be related to this issue:
https://github.com/ForFunLabs/ElevenPublicBugsAndAsks/issues/5#issue-448484133
(but i think i gave ai more than 5 seconds to serve, in case it was its turn)

**Comment by carrotstien** [comment]
yea this is related to the ai serve being interrupted. I need to update this process all together. The AI should effectively try to pull the ball into it's hand. Then, once the ball is in it's hand, do a serve with a real toss. 

Right now it's kind of a side scheduled task, so something is messing up. 

Usually this can be avoided by not hitting the ball once the point is over.

**Comment by carrotstien** [comment]
does this still happen after 0.9.3?

**Comment by ab050505** [comment]
i'll try to reproduce it tomorrow (hasn't happened yet in the few routine
games that i've played with ai so far though).

**Comment by ab050505** [comment]
happened again today with 0.14.0 on pc/rift. don't remember what happened exactly again but the ball ended up in the far left corner of the studio and the game (with world class ai) stopped. as far as i can remember, it was ai's turn to serve next but it just stood there (and i couldn't respawn the ball either). as per the message on the tv ("ball hit - hitter side"), i guess what happened was basically as per stownie's description earlier: "hit into the net, drop down on same side, score not counted, cant respawn ball", but with the difference that the score (or my point loss) seemed to get counted this time. made a recording of the aftermath (link below). one new detail is that by the time i started recording, the ball, which had seemed to be just lying in that corner, disappeared altogether. but after i tried a few things, the ball re-appeared in the far left corner and then disappeared again, as can be seen in the video (after i ended the game and started another one, the ai behaved normally again):
https://streamable.com/30r6a

**Comment by carrotstien** [comment]
i believe this is fixed now
