### ISSUE TITLE
[Bug] AI seems to choose complicated trajectory

### ISSUE THREAD

**Issue by Llamalland** [ForFunLabs/ElevenPublicBugsAndAsks#92]
Playing against the perfect easy AI, if I smash hits to the point where they retreat quite close to the wall, a reasonable amount of times (often enough that it seemed unlikely to be a random result of a glitch), the AI hit the ball so it rebounded against the beam above and behind me, into my side of the table, so I wonder whether it's possible that this trajectory is "intended".

**Comment by carrotstien** [comment]
the way the ai calculates the shot, does not include any colliders - it is purely the fixed geometry of the table. However, the ai does calculate the ball's path to it, from your paddle - so you can hit it off of the wall and if it lands on the opponent's table, ai will hit it back. 

I think what you are describing is a fluke..that's my best guess :|
