### ISSUE TITLE
[Suggestion] In free hit with AI, include a way to instruct AI to serve.

### ISSUE THREAD

**Issue by Llamalland** [ForFunLabs/ElevenPublicBugsAndAsks#93]
Some button, gesture, whatever, I just think it would be good if you could make the AI serve in free hit instead of always serving.

**Comment by carrotstien** [comment]
@Llamalland  thinking about different ways to do this. 

1. just a mode where when the ball is not hit in X time (or hits a non paddle x times), the ai will just serve
2. have you press a button on the controller to trigger a serve
3. have you trigger a serve by tossing the ball at the ai's side
other?

**Comment by Llamalland** [comment]
My favourite is 2 - long term, binding different buttons to different types
of serve could be cool too. 3 is fine too and could be done with 2, but
some people might want to preserve the ability to throw the ball at the AI
and have them return that, possible checkbox option?

I could see 1 being annoying if you're adjusting something or thinking or
whatever, if it were an option, I'd turn it off if possible.

**Comment by ab050505** [comment]
Also how about an on-screen toggle button (may be similar to ranked/unranked in legacy) saying "I will serve" / "Let AI serve" (or some such)? Beginners* might be a lot more comfortable with this. In fact, it should be possible to do as many things as possible via simple point-and-click.

*including people who are not used to gaming in general (as might be the case with many quest users)

**Comment by captnchr1s** [comment]
My favorite is option 3. Seems to be the most natural one in VR for me.

**Comment by carrotstien** [comment]
added v 0.36.0
