### ISSUE TITLE
Ball machine sometimes shoots only to its right (perpendicular)

### ISSUE THREAD

**Issue by Llamalland** [ForFunLabs/ElevenPublicBugsAndAsks#95]
I've had 3 or 4 times where the ball machine starts (without provocation or any spread sliders being greater than 0) shooting balls to its right (my left) perpendicular to its opening. This has happened on extreme low spin experiments I've been doing, but I've been doing that a lot, so might be unrelated.

**Comment by carrotstien** [comment]
@Llamalland , just want to make sure, when you say 0, that doesn't mean left most position on the sliders...it means middle position. ...except for speed.

**Comment by Llamalland** [comment]
Sorry, bad wording. I mean just the spread sliders are at zero, so no
variance is intended. I'll replicate bug and take a screenshot tonight.

**Comment by Llamalland** [comment]
![image](https://user-images.githubusercontent.com/38714700/62295112-824cf680-b4ab-11e9-8124-9e27ceee0455.png)

Horizontal spread may be the culprit - it seems like in the middle makes it 0 spread and below 0 makes it not spread but do weird things.

**Comment by carrotstien** [comment]
closing as ball machine is completely different now
