### ISSUE TITLE
[Bug] Left hand paddle  looses tracking

### ISSUE THREAD

**Issue by Simssmith** [ForFunLabs/ElevenPublicBugsAndAsks#96]
When change the paddle to use left hand I am observing strange behavior.  

The controller can't track the ball and paddle.  It causes serves to be missed and hits are not in sync.  My battery is 90% on both controllers. 

I read about other people having tracking issue with left hand controller after the latest Quest update. This might not be related to Eleven but a general Quest issue.  If any of you play left handed are you observing this issue?

**Comment by carrotstien** [comment]
@Simssmith  are you still having this issue? If you do, try to switch hands a few times to 'refresh' the collider. Does it happen after that?

**Comment by Simssmith** [comment]
@carrotstien yes and I tried but still no difference. We need few more left hand tester to confirm this issue is isolated to me or it is a real issue.

**Comment by carrotstien** [comment]
please try now as of 0.9.3

**Comment by Simssmith** [comment]
Much improved and ball stays in sync. However there is a new issue with the new patch. The table is too far away. I can't set the position of the table using 'reset view' as I was able to do in the previous version.

**Comment by carrotstien** [comment]
Use the in game reset view, vs the platform one. For Oculus it's pressing
and holding the button on either controller that doesn't open the menu

**Comment by Simssmith** [comment]
That worked. Left hand issue is almost gone. I am closing this bug.
